In [6]:
# 동작유무가 중요한게 아님, 결과를 개선하는 방식으로 반복
print("hello world")

hello world

In [ ]:
# 자료구조 (리스트, 딕셔너리, 튜플, 셋)
a = [1,4,6,2,7,8] # 값만 포함
print(a)
print(type(a))

[1, 4, 6, 2, 7, 8]
<class 'list'>

In [12]:
# 딕셔너리 json
b = {"name":"가나다", "age":13}
print(b)
print(type(b))

{'name': '가나다', 'age': 13}
<class 'dict'>

In [14]:
# 셋
c = {1, 2, 3, 4, 1, 2}
print(c)
print(type(c))

{1, 2, 3, 4}
<class 'set'>

In [16]:
# 튜플 (값을 변경할 수 없음)
d = (1,2,3,4)
print(d)
print(type(d))

(1, 2, 3, 4)
<class 'tuple'>

In [2]:
# 리스트 + 딕셔너리
e = [{"name":"가1", "age":13}, {"name":"나2", "age":23}, {"name":"다2", "age":33}]
print(type(e))

<class 'list'>

In [3]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3

In [11]:
import pymysql

connection = pymysql.connect(
    host = "127.0.0.1",
    port = 13306,
    user = "root",
    password = "1234",
    db="db1",
    cursorclass=pymysql.cursors.DictCursor
)

cursor = connection.cursor()

print(connection)

<pymysql.connections.Connection object at 0x000001FAFBFF8CD0>

In [ ]:
sql = "SELECT b.* FROM board b"
cursor.execute(sql)

rows = cursor.fetchall()
# [{},{},{}] : 리스트에 딕셔너리가 들어간 형태 cursorclass
rows

In [ ]:
import pandas as pd
df = pd.DataFrame(rows)
df

In [14]:
df.to_csv('./csv/borad.csv')

In [ ]:
sql = "SELECT c.* FROM customer c"
cursor.execute(sql)

rows = cursor.fetchall()
df = pd.DataFrame(rows)
df.to_csv('./csv/customer.csv')

---

In [21]:
import pandas
df = pandas.read_csv('./csv/customer.csv')
df

,Unnamed: 0,email,phone,password,name,create_at
0,0,a@a.com,NaN,NaN,NaN,2026-04-27 15:19:52
1,1,a10@a10.com,010-9999-0000,$2b$10$LJS0hOCzwDgaFdXAS3NPFef1sW/J7Vti1xQgwKf...,abcMan,2026-05-08 10:08:34
2,2,a3,010-0000-5673,$2b$10$hlY1B2uGftRnnG1Ttwpn5OTIZvLB6oBQYcp7ODo...,마바사,2026-05-11 11:42:14
3,3,abc@abc.com,010-0000-4321,$2b$10$yhPSnuqW2XtiR.ExMMD/yuxdGoMeVifXT99WCy4...,ABC,2026-04-29 11:35:18
4,4,abcd@abdc.com,010-1100-4321,$2b$10$NWmke7shNGNulV18aJVEdus0SXDeYXKS1KoAnR7...,ABCd,2026-04-29 11:35:50
...,...,...,...,...,...,...
56,56,user50@test.com,010-1000-0050,$2b$10$e8hz1AyndvLzX4uUtq6T/.k5yYjVq0UDI7/7NYH...,고객50,2026-04-27 16:29:05
57,57,user6@test.com,010-1000-0006,$2b$10$vQGt89wTCDgNC8GDrQASfuvo2kWUChpVJkFVGEQ...,고객6,2026-04-27 16:29:05
58,58,user7@test.com,010-1000-0007,$2b$10$nSSkibsEs5NnR4969Wy1N.dmgAM9YcQ2DUZO.lX...,고객7,2026-04-27 16:29:05
59,59,user8@test.com,010-0000-4444,$2b$10$.jKNsM0NalrapCTtJiq9beAn.TQOpPplfNFWzSE...,고객놈,2026-04-27 16:29:05
60,60,user9@test.com,NaN,NaN,고객9,2026-04-27 16:29:05

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  61 non-null     int64
 1   email       61 non-null     object
 2   phone       59 non-null     object
 3   password    59 non-null     object
 4   name        60 non-null     object
 5   create_at   61 non-null     object
dtypes: int64(1), object(5)
memory usage: 3.0+ KB

In [22]:
import pandas as pd
customer_master = pd.read_csv("http://114.207.245.181:13000/csv/customer_master.csv")
customer_master

,customer_id,customer_name,registration_date,email,gender,age,birth,pref
0,IK152942,김서준,2019-01-01 0:25,hirata_yuujirou@example.com,M,29,1990-06-10,대전광역시
1,TS808488,김예준,2019-01-01 1:13,tamura_shiori@example.com,F,33,1986-05-20,인천광역시
2,AS834628,김도윤,2019-01-01 2:00,hisano_yuki@example.com,F,63,1956-01-02,광주광역시
3,AS345469,김시우,2019-01-01 4:48,tsuruoka_kaoru@example.com,M,74,1945-03-25,인천광역시
4,GD892565,김주원,2019-01-01 4:54,oouchi_takashi@example.com,M,54,1965-08-05,울산광역시
...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52,hirayama_risa@example.com,F,77,1941-10-17,대전광역시
4996,HD758694,정영훈,2019-07-31 19:09,nakahara_mahiru@example.com,F,27,1991-11-13,광주광역시
4997,PL538517,정준기,2019-07-31 19:30,tabata_yuu1@example.com,F,73,1945-12-28,대전광역시
4998,OA955088,정도형,2019-07-31 22:32,setouchi_hikaru@example.com,F,75,1944-04-09,부산광역시
4999,HI349563,정지석,2019-07-31 22:49,horii_kanji@example.com,M,21,1998-02-06,서울특별시

In [23]:
customer_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   object
 1   customer_name      5000 non-null   object
 2   registration_date  5000 non-null   object
 3   email              5000 non-null   object
 4   gender             5000 non-null   object
 5   age                5000 non-null   int64
 6   birth              5000 non-null   object
 7   pref               5000 non-null   object
dtypes: int64(1), object(7)
memory usage: 312.6+ KB

In [24]:
customer_master.columns

Index(['customer_id', 'customer_name', 'registration_date', 'email', 'gender',
       'age', 'birth', 'pref'],
      dtype='object')

In [45]:
# 딕셔너리 타입으로 앞쪽에 원래:변경
t1 = {'customer_id':'고객아이디', 'customer_name':'고객명',
      'registration_date':'가입일', 'email':'이메일',
      'gender':'성별', 'age':'나이',
      'birth':'생일', 'pref':'지역'}

customer_master = customer_master.rename(columns=t1)

t1 = {'고객아이디':'고객아이디', '고객명':'고객명',
      '등록일자':'등록일', '이메일':'이메일',
      '성별':'성별', '나이':'나이',
      '생일':'생년월일', '지역':'지역'}
customer_master = customer_master.rename(columns=t1)
customer_master

,고객아이디,고객명,등록일,이메일,성별,나이,생년월일,지역
0,IK152942,김서준,2019-01-01 0:25,hirata_yuujirou@example.com,M,29,1990-06-10,대전광역시
1,TS808488,김예준,2019-01-01 1:13,tamura_shiori@example.com,F,33,1986-05-20,인천광역시
2,AS834628,김도윤,2019-01-01 2:00,hisano_yuki@example.com,F,63,1956-01-02,광주광역시
3,AS345469,김시우,2019-01-01 4:48,tsuruoka_kaoru@example.com,M,74,1945-03-25,인천광역시
4,GD892565,김주원,2019-01-01 4:54,oouchi_takashi@example.com,M,54,1965-08-05,울산광역시
...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52,hirayama_risa@example.com,F,77,1941-10-17,대전광역시
4996,HD758694,정영훈,2019-07-31 19:09,nakahara_mahiru@example.com,F,27,1991-11-13,광주광역시
4997,PL538517,정준기,2019-07-31 19:30,tabata_yuu1@example.com,F,73,1945-12-28,대전광역시
4998,OA955088,정도형,2019-07-31 22:32,setouchi_hikaru@example.com,F,75,1944-04-09,부산광역시
4999,HI349563,정지석,2019-07-31 22:49,horii_kanji@example.com,M,21,1998-02-06,서울특별시

In [51]:
customer_master.dtypes

고객아이디            object
고객명              object
등록일      datetime64[ns]
이메일              object
성별               object
나이                int64
생년월일     datetime64[ns]
지역               object
dtype: object

In [50]:
# 현재 등록일의 타입이 문자인데 날짜 타입으로 변환하기
customer_master['등록일'] = pd.to_datetime(customer_master['등록일'], format='%Y-%m-%d %H:%M')
customer_master['생년월일'] = pd.to_datetime(customer_master['생년월일'], format='%Y-%m-%d')

In [52]:
# 생년월일 컬럼에서 년만 추출해서 새로운 컬럼 "년" 생성
customer_master['년'] = customer_master['생년월일'].dt.year
customer_master['월'] = customer_master['생년월일'].dt.month
customer_master['일'] = customer_master['생년월일'].dt.day
customer_master

,고객아이디,고객명,등록일,이메일,성별,나이,생년월일,지역,년,월,일
0,IK152942,김서준,2019-01-01 00:25:00,hirata_yuujirou@example.com,M,29,1990-06-10,대전광역시,1990,6,10
1,TS808488,김예준,2019-01-01 01:13:00,tamura_shiori@example.com,F,33,1986-05-20,인천광역시,1986,5,20
2,AS834628,김도윤,2019-01-01 02:00:00,hisano_yuki@example.com,F,63,1956-01-02,광주광역시,1956,1,2
3,AS345469,김시우,2019-01-01 04:48:00,tsuruoka_kaoru@example.com,M,74,1945-03-25,인천광역시,1945,3,25
4,GD892565,김주원,2019-01-01 04:54:00,oouchi_takashi@example.com,M,54,1965-08-05,울산광역시,1965,8,5
...,...,...,...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52:00,hirayama_risa@example.com,F,77,1941-10-17,대전광역시,1941,10,17
4996,HD758694,정영훈,2019-07-31 19:09:00,nakahara_mahiru@example.com,F,27,1991-11-13,광주광역시,1991,11,13
4997,PL538517,정준기,2019-07-31 19:30:00,tabata_yuu1@example.com,F,73,1945-12-28,대전광역시,1945,12,28
4998,OA955088,정도형,2019-07-31 22:32:00,setouchi_hikaru@example.com,F,75,1944-04-09,부산광역시,1944,4,9
4999,HI349563,정지석,2019-07-31 22:49:00,horii_kanji@example.com,M,21,1998-02-06,서울특별시,1998,2,6

In [53]:
# 나이 다시 계산하기
customer_master['나이'] = 2026 - customer_master['년'] + 1
customer_master

,고객아이디,고객명,등록일,이메일,성별,나이,생년월일,지역,년,월,일
0,IK152942,김서준,2019-01-01 00:25:00,hirata_yuujirou@example.com,M,37,1990-06-10,대전광역시,1990,6,10
1,TS808488,김예준,2019-01-01 01:13:00,tamura_shiori@example.com,F,41,1986-05-20,인천광역시,1986,5,20
2,AS834628,김도윤,2019-01-01 02:00:00,hisano_yuki@example.com,F,71,1956-01-02,광주광역시,1956,1,2
3,AS345469,김시우,2019-01-01 04:48:00,tsuruoka_kaoru@example.com,M,82,1945-03-25,인천광역시,1945,3,25
4,GD892565,김주원,2019-01-01 04:54:00,oouchi_takashi@example.com,M,62,1965-08-05,울산광역시,1965,8,5
...,...,...,...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52:00,hirayama_risa@example.com,F,86,1941-10-17,대전광역시,1941,10,17
4996,HD758694,정영훈,2019-07-31 19:09:00,nakahara_mahiru@example.com,F,36,1991-11-13,광주광역시,1991,11,13
4997,PL538517,정준기,2019-07-31 19:30:00,tabata_yuu1@example.com,F,82,1945-12-28,대전광역시,1945,12,28
4998,OA955088,정도형,2019-07-31 22:32:00,setouchi_hikaru@example.com,F,83,1944-04-09,부산광역시,1944,4,9
4999,HI349563,정지석,2019-07-31 22:49:00,horii_kanji@example.com,M,29,1998-02-06,서울특별시,1998,2,6

In [56]:
bins = [0, 9, 19, 29, 39, 49, 59, 69, 79, 150]
labels = ["0대", "10대", "20대", "30대", "40대", "50대", "60대", "70대", "초고령"]
customer_master['연령대'] = pd.cut(customer_master['나이'], bins=bins, labels=labels, right=True)
customer_master

,고객아이디,고객명,등록일,이메일,성별,나이,생년월일,지역,년,월,일,연령대
0,IK152942,김서준,2019-01-01 00:25:00,hirata_yuujirou@example.com,M,37,1990-06-10,대전광역시,1990,6,10,30대
1,TS808488,김예준,2019-01-01 01:13:00,tamura_shiori@example.com,F,41,1986-05-20,인천광역시,1986,5,20,40대
2,AS834628,김도윤,2019-01-01 02:00:00,hisano_yuki@example.com,F,71,1956-01-02,광주광역시,1956,1,2,70대
3,AS345469,김시우,2019-01-01 04:48:00,tsuruoka_kaoru@example.com,M,82,1945-03-25,인천광역시,1945,3,25,초고령
4,GD892565,김주원,2019-01-01 04:54:00,oouchi_takashi@example.com,M,62,1965-08-05,울산광역시,1965,8,5,60대
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52:00,hirayama_risa@example.com,F,86,1941-10-17,대전광역시,1941,10,17,초고령
4996,HD758694,정영훈,2019-07-31 19:09:00,nakahara_mahiru@example.com,F,36,1991-11-13,광주광역시,1991,11,13,30대
4997,PL538517,정준기,2019-07-31 19:30:00,tabata_yuu1@example.com,F,82,1945-12-28,대전광역시,1945,12,28,초고령
4998,OA955088,정도형,2019-07-31 22:32:00,setouchi_hikaru@example.com,F,83,1944-04-09,부산광역시,1944,4,9,초고령
4999,HI349563,정지석,2019-07-31 22:49:00,horii_kanji@example.com,M,29,1998-02-06,서울특별시,1998,2,6,20대

In [61]:
# 데이터프레임 customer_master 객체를 파일로 저장하기
customer_master.to_pickle('./pkl/customer_master.pkl')

In [ ]:
import pandas as pd
customer_master = pd.read_pickle('./pkl/customer_master.pkl')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객아이디   5000 non-null   object
 1   고객명     5000 non-null   object
 2   등록일     5000 non-null   datetime64[ns]
 3   이메일     5000 non-null   object
 4   성별      5000 non-null   object
 5   나이      5000 non-null   int32
 6   생년월일    5000 non-null   datetime64[ns]
 7   지역      5000 non-null   object
 8   년       5000 non-null   int32
 9   월       5000 non-null   int32
 10  일       5000 non-null   int32
 11  연령대     5000 non-null   category
dtypes: category(1), datetime64[ns](2), int32(4), object(5)
memory usage: 356.6+ KB

In [64]:
# 물품 정보 일기
item_master = pd.read_csv('http://114.207.245.181:13000/csv/item_master.csv')
item_master

  item_id item_name  item_price
0    S001      PC-A       50000
1    S002      PC-B       85000
2    S003      PC-C      120000
3    S004      PC-D      180000
4    S005      PC-E      210000

In [65]:
item_master.columns

Index(['item_id', 'item_name', 'item_price'], dtype='object')

In [66]:
t1 = { 'item_id':'물품코드', 'item_name':'물품명', 'item_price':'물품가격' }
item_master = item_master.rename(columns=t1)
item_master

   물품코드   물품명    물품가격
0  S001  PC-A   50000
1  S002  PC-B   85000
2  S003  PC-C  120000
3  S004  PC-D  180000
4  S005  PC-E  210000

In [ ]:
# item_master 타입 확인
item_master.dtypes

물품코드    object
물품명     object
물품가격     int64
dtype: object

In [71]:
item_master.to_pickle('./pkl/item_master.pkl')

In [68]:
# 거래내역1 읽기
transaction_1 = pd.read_csv('http://114.207.245.181:13000/csv/transaction_1.csv')
transaction_1.head(3)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502
1    T0000000114   50000  2019-02-01 01:37:23    HD678019
2    T0000000115  120000  2019-02-01 02:34:19    HD298120

In [69]:
# 거래내역2 읽기
transaction_2 = pd.read_csv('http://114.207.245.181:13000/csv/transaction_2.csv')
transaction_2.head(3)

  transaction_id   price         payment_date customer_id
0    T0000005113  295000  2019-06-15 07:20:27    TS169261
1    T0000005114   50000  2019-06-15 07:35:47    HI599892
2    T0000005115   85000  2019-06-15 07:56:36    HI421757

In [ ]:
# transaction_1에 transaction_2를 붙이기
transaction = pd.concat([transaction_1, transaction_2], ignore_index=True)
transaction

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [72]:
transaction.columns

Index(['transaction_id', 'price', 'payment_date', 'customer_id'], dtype='object')

In [73]:
#컬럼명 변경하기
t1 = { 'transaction_id':'거래코드', 'price':'결제금액',
      'payment_date':'결제일', 'customer_id':'고객아이디' }
transaction = transaction.rename(columns=t1)
transaction

             거래코드    결제금액                  결제일     고객아이디
0     T0000000113  210000  2019-02-01 01:36:57  PL563502
1     T0000000114   50000  2019-02-01 01:37:23  HD678019
2     T0000000115  120000  2019-02-01 02:34:19  HD298120
3     T0000000116  210000  2019-02-01 02:47:23  IK452215
4     T0000000117  170000  2019-02-01 04:33:46  PL542865
...           ...     ...                  ...       ...
6781  T0000006894  180000  2019-07-31 21:20:44  HI400734
6782  T0000006895   85000  2019-07-31 21:52:48  AS339451
6783  T0000006896  100000  2019-07-31 23:35:25  OA027325
6784  T0000006897   85000  2019-07-31 23:39:35  TS624738
6785  T0000006898   85000  2019-07-31 23:41:38  AS834214

[6786 rows x 4 columns]

In [78]:
# 타입확인하기
transaction.dtypes

거래코드             object
결제금액              int64
결제일      datetime64[ns]
고객아이디            object
dtype: object

In [79]:
# 결제일을 날짜 타입으로 변환
transaction['결제일'] = pd.to_datetime(transaction['결제일'], format='%Y-%m-%d %H:%M:%S')

In [80]:
# transaction을 pkl로 저장
transaction.to_pickle('./pkl/transaction_master.pkl')