In [ ]:
! pip install pymongo

In [ ]:
import pymongo
pymongo.__version__

In [ ]:
# mongoDB에 연결하기
conn = pymongo.MongoClient("mongodb://admin:1234@localhost:27017/")
conn

In [ ]:
# db 선택하기 (없으면 자동으로 생성된)
db = conn.get_database("db1")
db

In [ ]:
#컬렉션 선택 (없으면 자동으로 생성) == 테이블
collection = db.get_collection("user")
collection

In [ ]:
from datetime import datetime

# 딕셔너리 타입으로 저장할 데이터 생성 (이메일, 암호, 이름, 나이, 등록일)
d1 = {
    "phone":"010-0000-1111",
    "email":"a", "password":"a", "name":"가나다", "age":23, "created_at":datetime.now()
}
collection.insert_one(d1)

In [46]:
import pandas as pd
df = pd.read_pickle('./pkl/customer_master.pkl')
df

,고객아이디,고객명,등록일,이메일,성별,나이,생년월일,지역,년,월,일,연령대
0,IK152942,김서준,2019-01-01 00:25:00,hirata_yuujirou@example.com,M,37,1990-06-10,대전광역시,1990,6,10,30대
1,TS808488,김예준,2019-01-01 01:13:00,tamura_shiori@example.com,F,41,1986-05-20,인천광역시,1986,5,20,40대
2,AS834628,김도윤,2019-01-01 02:00:00,hisano_yuki@example.com,F,71,1956-01-02,광주광역시,1956,1,2,70대
3,AS345469,김시우,2019-01-01 04:48:00,tsuruoka_kaoru@example.com,M,82,1945-03-25,인천광역시,1945,3,25,초고령
4,GD892565,김주원,2019-01-01 04:54:00,oouchi_takashi@example.com,M,62,1965-08-05,울산광역시,1965,8,5,60대
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52:00,hirayama_risa@example.com,F,86,1941-10-17,대전광역시,1941,10,17,초고령
4996,HD758694,정영훈,2019-07-31 19:09:00,nakahara_mahiru@example.com,F,36,1991-11-13,광주광역시,1991,11,13,30대
4997,PL538517,정준기,2019-07-31 19:30:00,tabata_yuu1@example.com,F,82,1945-12-28,대전광역시,1945,12,28,초고령
4998,OA955088,정도형,2019-07-31 22:32:00,setouchi_hikaru@example.com,F,83,1944-04-09,부산광역시,1944,4,9,초고령
4999,HI349563,정지석,2019-07-31 22:49:00,horii_kanji@example.com,M,29,1998-02-06,서울특별시,1998,2,6,20대

In [47]:
col_customer = db.get_collection("customer_master")
# df => [{},{},{}] => 딕셔너리 타입으로 변환 필요
t2 = df.to_dict(orient="records")

col_customer.insert_many(t2)

InsertManyResult([ObjectId('6a0567f75ea3054c2cea3e96'), ObjectId('6a0567f75ea3054c2cea3e97'), ObjectId('6a0567f75ea3054c2cea3e98'), ObjectId('6a0567f75ea3054c2cea3e99'), ObjectId('6a0567f75ea3054c2cea3e9a'), ObjectId('6a0567f75ea3054c2cea3e9b'), ObjectId('6a0567f75ea3054c2cea3e9c'), ObjectId('6a0567f75ea3054c2cea3e9d'), ObjectId('6a0567f75ea3054c2cea3e9e'), ObjectId('6a0567f75ea3054c2cea3e9f'), ObjectId('6a0567f75ea3054c2cea3ea0'), ObjectId('6a0567f75ea3054c2cea3ea1'), ObjectId('6a0567f75ea3054c2cea3ea2'), ObjectId('6a0567f75ea3054c2cea3ea3'), ObjectId('6a0567f75ea3054c2cea3ea4'), ObjectId('6a0567f75ea3054c2cea3ea5'), ObjectId('6a0567f75ea3054c2cea3ea6'), ObjectId('6a0567f75ea3054c2cea3ea7'), ObjectId('6a0567f75ea3054c2cea3ea8'), ObjectId('6a0567f75ea3054c2cea3ea9'), ObjectId('6a0567f75ea3054c2cea3eaa'), ObjectId('6a0567f75ea3054c2cea3eab'), ObjectId('6a0567f75ea3054c2cea3eac'), ObjectId('6a0567f75ea3054c2cea3ead'), ObjectId('6a0567f75ea3054c2cea3eae'), ObjectId('6a0567f75ea3054c2cea3eaf'), ObjectId('6a0567f75ea3054c2cea3eb0'), ObjectId('6a0567f75ea3054c2cea3eb1'), ObjectId('6a0567f75ea3054c2cea3eb2'), ObjectId('6a0567f75ea3054c2cea3eb3'), ObjectId('6a0567f75ea3054c2cea3eb4'), ObjectId('6a0567f75ea3054c2cea3eb5'), ObjectId('6a0567f75ea3054c2cea3eb6'), ObjectId('6a0567f75ea3054c2cea3eb7'), ObjectId('6a0567f75ea3054c2cea3eb8'), ObjectId('6a0567f75ea3054c2cea3eb9'), ObjectId('6a0567f75ea3054c2cea3eba'), ObjectId('6a0567f75ea3054c2cea3ebb'), ObjectId('6a0567f75ea3054c2cea3ebc'), ObjectId('6a0567f75ea3054c2cea3ebd'), ObjectId('6a0567f75ea3054c2cea3ebe'), ObjectId('6a0567f75ea3054c2cea3ebf'), ObjectId('6a0567f75ea3054c2cea3ec0'), ObjectId('6a0567f75ea3054c2cea3ec1'), ObjectId('6a0567f75ea3054c2cea3ec2'), ObjectId('6a0567f75ea3054c2cea3ec3'), ObjectId('6a0567f75ea3054c2cea3ec4'), ObjectId('6a0567f75ea3054c2cea3ec5'), ObjectId('6a0567f75ea3054c2cea3ec6'), ObjectId('6a0567f75ea3054c2cea3ec7'), ObjectId('6a0567f75ea3054c2cea3ec8'), ObjectId('6a0567f75ea3054c2cea3ec9'), ObjectId('6a0567f75ea3054c2cea3eca'), ObjectId('6a0567f75ea3054c2cea3ecb'), ObjectId('6a0567f75ea3054c2cea3ecc'), ObjectId('6a0567f75ea3054c2cea3ecd'), ObjectId('6a0567f75ea3054c2cea3ece'), ObjectId('6a0567f75ea3054c2cea3ecf'), ObjectId('6a0567f75ea3054c2cea3ed0'), ObjectId('6a0567f75ea3054c2cea3ed1'), ObjectId('6a0567f75ea3054c2cea3ed2'), ObjectId('6a0567f75ea3054c2cea3ed3'), ObjectId('6a0567f75ea3054c2cea3ed4'), ObjectId('6a0567f75ea3054c2cea3ed5'), ObjectId('6a0567f75ea3054c2cea3ed6'), ObjectId('6a0567f75ea3054c2cea3ed7'), ObjectId('6a0567f75ea3054c2cea3ed8'), ObjectId('6a0567f75ea3054c2cea3ed9'), ObjectId('6a0567f75ea3054c2cea3eda'), ObjectId('6a0567f75ea3054c2cea3edb'), ObjectId('6a0567f75ea3054c2cea3edc'), ObjectId('6a0567f75ea3054c2cea3edd'), ObjectId('6a0567f75ea3054c2cea3ede'), ObjectId('6a0567f75ea3054c2cea3edf'), ObjectId('6a0567f75ea3054c2cea3ee0'), ObjectId('6a0567f75ea3054c2cea3ee1'), ObjectId('6a0567f75ea3054c2cea3ee2'), ObjectId('6a0567f75ea3054c2cea3ee3'), ObjectId('6a0567f75ea3054c2cea3ee4'), ObjectId('6a0567f75ea3054c2cea3ee5'), ObjectId('6a0567f75ea3054c2cea3ee6'), ObjectId('6a0567f75ea3054c2cea3ee7'), ObjectId('6a0567f75ea3054c2cea3ee8'), ObjectId('6a0567f75ea3054c2cea3ee9'), ObjectId('6a0567f75ea3054c2cea3eea'), ObjectId('6a0567f75ea3054c2cea3eeb'), ObjectId('6a0567f75ea3054c2cea3eec'), ObjectId('6a0567f75ea3054c2cea3eed'), ObjectId('6a0567f75ea3054c2cea3eee'), ObjectId('6a0567f75ea3054c2cea3eef'), ObjectId('6a0567f75ea3054c2cea3ef0'), ObjectId('6a0567f75ea3054c2cea3ef1'), ObjectId('6a0567f75ea3054c2cea3ef2'), ObjectId('6a0567f75ea3054c2cea3ef3'), ObjectId('6a0567f75ea3054c2cea3ef4'), ObjectId('6a0567f75ea3054c2cea3ef5'), ObjectId('6a0567f75ea3054c2cea3ef6'), ObjectId('6a0567f75ea3054c2cea3ef7'), ObjectId('6a0567f75ea3054c2cea3ef8'), ObjectId('6a0567f75ea3054c2cea3ef9'), ObjectId('6a0567f75ea3054c2cea3efa'), ObjectId('6a0567f75ea3054c2cea3efb'), ObjectId('6a0567f75ea3054c2cea3efc'), ObjectId('6a0567f75ea3054c2cea3efd'), ObjectId('6a0567f75ea3054c2cea3efe'), ObjectId('6a0567f75ea3054c2cea3eff'), ObjectId('6a0567f75ea3054c2cea3f00'), ObjectId('6a0567f75ea3054c2cea3f01'), ObjectId('6a0567f75ea3054c2cea3f02'), ObjectId('6a0567f75ea3054c2cea3f03'), ObjectId('6a0567f75ea3054c2cea3f04'), ObjectId('6a0567f75ea3054c2cea3f05'), ObjectId('6a0567f75ea3054c2cea3f06'), ObjectId('6a0567f75ea3054c2cea3f07'), ObjectId('6a0567f75ea3054c2cea3f08'), ObjectId('6a0567f75ea3054c2cea3f09'), ObjectId('6a0567f75ea3054c2cea3f0a'), ObjectId('6a0567f75ea3054c2cea3f0b'), ObjectId('6a0567f75ea3054c2cea3f0c'), ObjectId('6a0567f75ea3054c2cea3f0d'), ObjectId('6a0567f75ea3054c2cea3f0e'), ObjectId('6a0567f75ea3054c2cea3f0f'), ObjectId('6a0567f75ea3054c2cea3f10'), ObjectId('6a0567f75ea3054c2cea3f11'), ObjectId('6a0567f75ea3054c2cea3f12'), ObjectId('6a0567f75ea3054c2cea3f13'), ObjectId('6a0567f75ea3054c2cea3f14'), ObjectId('6a0567f75ea3054c2cea3f15'), ObjectId('6a0567f75ea3054c2cea3f16'), ObjectId('6a0567f75ea3054c2cea3f17'), ObjectId('6a0567f75ea3054c2cea3f18'), ObjectId('6a0567f75ea3054c2cea3f19'), ObjectId('6a0567f75ea3054c2cea3f1a'), ObjectId('6a0567f75ea3054c2cea3f1b'), ObjectId('6a0567f75ea3054c2cea3f1c'), ObjectId('6a0567f75ea3054c2cea3f1d'), ObjectId('6a0567f75ea3054c2cea3f1e'), ObjectId('6a0567f75ea3054c2cea3f1f'), ObjectId('6a0567f75ea3054c2cea3f20'), ObjectId('6a0567f75ea3054c2cea3f21'), ObjectId('6a0567f75ea3054c2cea3f22'), ObjectId('6a0567f75ea3054c2cea3f23'), ObjectId('6a0567f75ea3054c2cea3f24'), ObjectId('6a0567f75ea3054c2cea3f25'), ObjectId('6a0567f75ea3054c2cea3f26'), ObjectId('6a0567f75ea3054c2cea3f27'), ObjectId('6a0567f75ea3054c2cea3f28'), ObjectId('6a0567f75ea3054c2cea3f29'), ObjectId('6a0567f75ea3054c2cea3f2a'), ObjectId('6a0567f75ea3054c2cea3f2b'), ObjectId('6a0567f75ea3054c2cea3f2c'), ObjectId('6a0567f75ea3054c2cea3f2d'), ObjectId('6a0567f75ea3054c2cea3f2e'), ObjectId('6a0567f75ea3054c2cea3f2f'), ObjectId('6a0567f75ea3054c2cea3f30'), ObjectId('6a0567f75ea3054c2cea3f31'), ObjectId('6a0567f75ea3054c2cea3f32'), ObjectId('6a0567f75ea3054c2cea3f33'), ObjectId('6a0567f75ea3054c2cea3f34'), ObjectId('6a0567f75ea3054c2cea3f35'), ObjectId('6a0567f75ea3054c2cea3f36'), ObjectId('6a0567f75ea3054c2cea3f37'), ObjectId('6a0567f75ea3054c2cea3f38'), ObjectId('6a0567f75ea3054c2cea3f39'), ObjectId('6a0567f75ea3054c2cea3f3a'), ObjectId('6a0567f75ea3054c2cea3f3b'), ObjectId('6a0567f75ea3054c2cea3f3c'), ObjectId('6a0567f75ea3054c2cea3f3d'), ObjectId('6a0567f75ea3054c2cea3f3e'), ObjectId('6a0567f75ea3054c2cea3f3f'), ObjectId('6a0567f75ea3054c2cea3f40'), ObjectId('6a0567f75ea3054c2cea3f41'), ObjectId('6a0567f75ea3054c2cea3f42'), ObjectId('6a0567f75ea3054c2cea3f43'), ObjectId('6a0567f75ea3054c2cea3f44'), ObjectId('6a0567f75ea3054c2cea3f45'), ObjectId('6a0567f75ea3054c2cea3f46'), ObjectId('6a0567f75ea3054c2cea3f47'), ObjectId('6a0567f75ea3054c2cea3f48'), ObjectId('6a0567f75ea3054c2cea3f49'), ObjectId('6a0567f75ea3054c2cea3f4a'), ObjectId('6a0567f75ea3054c2cea3f4b'), ObjectId('6a0567f75ea3054c2cea3f4c'), ObjectId('6a0567f75ea3054c2cea3f4d'), ObjectId('6a0567f75ea3054c2cea3f4e'), ObjectId('6a0567f75ea3054c2cea3f4f'), ObjectId('6a0567f75ea3054c2cea3f50'), ObjectId('6a0567f75ea3054c2cea3f51'), ObjectId('6a0567f75ea3054c2cea3f52'), ObjectId('6a0567f75ea3054c2cea3f53'), ObjectId('6a0567f75ea3054c2cea3f54'), ObjectId('6a0567f75ea3054c2cea3f55'), ObjectId('6a0567f75ea3054c2cea3f56'), ObjectId('6a0567f75ea3054c2cea3f57'), ObjectId('6a0567f75ea3054c2cea3f58'), ObjectId('6a0567f75ea3054c2cea3f59'), ObjectId('6a0567f75ea3054c2cea3f5a'), ObjectId('6a0567f75ea3054c2cea3f5b'), ObjectId('6a0567f75ea3054c2cea3f5c'), ObjectId('6a0567f75ea3054c2cea3f5d'), ObjectId('6a0567f75ea3054c2cea3f5e'), ObjectId('6a0567f75ea3054c2cea3f5f'), ObjectId('6a0567f75ea3054c2cea3f60'), ObjectId('6a0567f75ea3054c2cea3f61'), ObjectId('6a0567f75ea3054c2cea3f62'), ObjectId('6a0567f75ea3054c2cea3f63'), ObjectId('6a0567f75ea3054c2cea3f64'), ObjectId('6a0567f75ea3054c2cea3f65'), ObjectId('6a0567f75ea3054c2cea3f66'), ObjectId('6a0567f75ea3054c2cea3f67'), ObjectId('6a0567f75ea3054c2cea3f68'), ObjectId('6a0567f75ea3054c2cea3f69'), ObjectId('6a0567f75ea3054c2cea3f6a'), ObjectId('6a0567f75ea3054c2cea3f6b'), ObjectId('6a0567f75ea3054c2cea3f6c'), ObjectId('6a0567f75ea3054c2cea3f6d'), ObjectId('6a0567f75ea3054c2cea3f6e'), ObjectId('6a0567f75ea3054c2cea3f6f'), ObjectId('6a0567f75ea3054c2cea3f70'), ObjectId('6a0567f75ea3054c2cea3f71'), ObjectId('6a0567f75ea3054c2cea3f72'), ObjectId('6a0567f75ea3054c2cea3f73'), ObjectId('6a0567f75ea3054c2cea3f74'), ObjectId('6a0567f75ea3054c2cea3f75'), ObjectId('6a0567f75ea3054c2cea3f76'), ObjectId('6a0567f75ea3054c2cea3f77'), ObjectId('6a0567f75ea3054c2cea3f78'), ObjectId('6a0567f75ea3054c2cea3f79'), ObjectId('6a0567f75ea3054c2cea3f7a'), ObjectId('6a0567f75ea3054c2cea3f7b'), ObjectId('6a0567f75ea3054c2cea3f7c'), ObjectId('6a0567f75ea3054c2cea3f7d'), ObjectId('6a0567f75ea3054c2cea3f7e'), ObjectId('6a0567f75ea3054c2cea3f7f'), ObjectId('6a0567f75ea3054c2cea3f80'), ObjectId('6a0567f75ea3054c2cea3f81'), ObjectId('6a0567f75ea3054c2cea3f82'), ObjectId('6a0567f75ea3054c2cea3f83'), ObjectId('6a0567f75ea3054c2cea3f84'), ObjectId('6a0567f75ea3054c2cea3f85'), ObjectId('6a0567f75ea3054c2cea3f86'), ObjectId('6a0567f75ea3054c2cea3f87'), ObjectId('6a0567f75ea3054c2cea3f88'), ObjectId('6a0567f75ea3054c2cea3f89'), ObjectId('6a0567f75ea3054c2cea3f8a'), ObjectId('6a0567f75ea3054c2cea3f8b'), ObjectId('6a0567f75ea3054c2cea3f8c'), ObjectId('6a0567f75ea3054c2cea3f8d'), ObjectId('6a0567f75ea3054c2cea3f8e'), ObjectId('6a0567f75ea3054c2cea3f8f'), ObjectId('6a0567f75ea3054c2cea3f90'), ObjectId('6a0567f75ea3054c2cea3f91'), ObjectId('6a0567f75ea3054c2cea3f92'), ObjectId('6a0567f75ea3054c2cea3f93'), ObjectId('6a0567f75ea3054c2cea3f94'), ObjectId('6a0567f75ea3054c2cea3f95'), ObjectId('6a0567f75ea3054c2cea3f96'), ObjectId('6a0567f75ea3054c2cea3f97'), ObjectId('6a0567f75ea3054c2cea3f98'), ObjectId('6a0567f75ea3054c2cea3f99'), ObjectId('6a0567f75ea3054c2cea3f9a'), ObjectId('6a0567f75ea3054c2cea3f9b'), ObjectId('6a0567f75ea3054c2cea3f9c'), ObjectId('6a0567f75ea3054c2cea3f9d'), ObjectId('6a0567f75ea3054c2cea3f9e'), ObjectId('6a0567f75ea3054c2cea3f9f'), ObjectId('6a0567f75ea3054c2cea3fa0'), ObjectId('6a0567f75ea3054c2cea3fa1'), ObjectId('6a0567f75ea3054c2cea3fa2'), ObjectId('6a0567f75ea3054c2cea3fa3'), ObjectId('6a0567f75ea3054c2cea3fa4'), ObjectId('6a0567f75ea3054c2cea3fa5'), ObjectId('6a0567f75ea3054c2cea3fa6'), ObjectId('6a0567f75ea3054c2cea3fa7'), ObjectId('6a0567f75ea3054c2cea3fa8'), ObjectId('6a0567f75ea3054c2cea3fa9'), ObjectId('6a0567f75ea3054c2cea3faa'), ObjectId('6a0567f75ea3054c2cea3fab'), ObjectId('6a0567f75ea3054c2cea3fac'), ObjectId('6a0567f75ea3054c2cea3fad'), ObjectId('6a0567f75ea3054c2cea3fae'), ObjectId('6a0567f75ea3054c2cea3faf'), ObjectId('6a0567f75ea3054c2cea3fb0'), ObjectId('6a0567f75ea3054c2cea3fb1'), ObjectId('6a0567f75ea3054c2cea3fb2'), ObjectId('6a0567f75ea3054c2cea3fb3'), ObjectId('6a0567f75ea3054c2cea3fb4'), ObjectId('6a0567f75ea3054c2cea3fb5'), ObjectId('6a0567f75ea3054c2cea3fb6'), ObjectId('6a0567f75ea3054c2cea3fb7'), ObjectId('6a0567f75ea3054c2cea3fb8'), ObjectId('6a0567f75ea3054c2cea3fb9'), ObjectId('6a0567f75ea3054c2cea3fba'), ObjectId('6a0567f75ea3054c2cea3fbb'), ObjectId('6a0567f75ea3054c2cea3fbc'), ObjectId('6a0567f75ea3054c2cea3fbd'), ObjectId('6a0567f75ea3054c2cea3fbe'), ObjectId('6a0567f75ea3054c2cea3fbf'), ObjectId('6a0567f75ea3054c2cea3fc0'), ObjectId('6a0567f75ea3054c2cea3fc1'), ObjectId('6a0567f75ea3054c2cea3fc2'), ObjectId('6a0567f75ea3054c2cea3fc3'), ObjectId('6a0567f75ea3054c2cea3fc4'), ObjectId('6a0567f75ea3054c2cea3fc5'), ObjectId('6a0567f75ea3054c2cea3fc6'), ObjectId('6a0567f75ea3054c2cea3fc7'), ObjectId('6a0567f75ea3054c2cea3fc8'), ObjectId('6a0567f75ea3054c2cea3fc9'), ObjectId('6a0567f75ea3054c2cea3fca'), ObjectId('6a0567f75ea3054c2cea3fcb'), ObjectId('6a0567f75ea3054c2cea3fcc'), ObjectId('6a0567f75ea3054c2cea3fcd'), ObjectId('6a0567f75ea3054c2cea3fce'), ObjectId('6a0567f75ea3054c2cea3fcf'), ObjectId('6a0567f75ea3054c2cea3fd0'), ObjectId('6a0567f75ea3054c2cea3fd1'), ObjectId('6a0567f75ea3054c2cea3fd2'), ObjectId('6a0567f75ea3054c2cea3fd3'), ObjectId('6a0567f75ea3054c2cea3fd4'), ObjectId('6a0567f75ea3054c2cea3fd5'), ObjectId('6a0567f75ea3054c2cea3fd6'), ObjectId('6a0567f75ea3054c2cea3fd7'), ObjectId('6a0567f75ea3054c2cea3fd8'), ObjectId('6a0567f75ea3054c2cea3fd9'), ObjectId('6a0567f75ea3054c2cea3fda'), ObjectId('6a0567f75ea3054c2cea3fdb'), ObjectId('6a0567f75ea3054c2cea3fdc'), ObjectId('6a0567f75ea3054c2cea3fdd'), ObjectId('6a0567f75ea3054c2cea3fde'), ObjectId('6a0567f75ea3054c2cea3fdf'), ObjectId('6a0567f75ea3054c2cea3fe0'), ObjectId('6a0567f75ea3054c2cea3fe1'), ObjectId('6a0567f75ea3054c2cea3fe2'), ObjectId('6a0567f75ea3054c2cea3fe3'), ObjectId('6a0567f75ea3054c2cea3fe4'), ObjectId('6a0567f75ea3054c2cea3fe5'), ObjectId('6a0567f75ea3054c2cea3fe6'), ObjectId('6a0567f75ea3054c2cea3fe7'), ObjectId('6a0567f75ea3054c2cea3fe8'), ObjectId('6a0567f75ea3054c2cea3fe9'), ObjectId('6a0567f75ea3054c2cea3fea'), ObjectId('6a0567f75ea3054c2cea3feb'), ObjectId('6a0567f75ea3054c2cea3fec'), ObjectId('6a0567f75ea3054c2cea3fed'), ObjectId('6a0567f75ea3054c2cea3fee'), ObjectId('6a0567f75ea3054c2cea3fef'), ObjectId('6a0567f75ea3054c2cea3ff0'), ObjectId('6a0567f75ea3054c2cea3ff1'), ObjectId('6a0567f75ea3054c2cea3ff2'), ObjectId('6a0567f75ea3054c2cea3ff3'), ObjectId('6a0567f75ea3054c2cea3ff4'), ObjectId('6a0567f75ea3054c2cea3ff5'), ObjectId('6a0567f75ea3054c2cea3ff6'), ObjectId('6a0567f75ea3054c2cea3ff7'), ObjectId('6a0567f75ea3054c2cea3ff8'), ObjectId('6a0567f75ea3054c2cea3ff9'), ObjectId('6a0567f75ea3054c2cea3ffa'), ObjectId('6a0567f75ea3054c2cea3ffb'), ObjectId('6a0567f75ea3054c2cea3ffc'), ObjectId('6a0567f75ea3054c2cea3ffd'), ObjectId('6a0567f75ea3054c2cea3ffe'), ObjectId('6a0567f75ea3054c2cea3fff'), ObjectId('6a0567f75ea3054c2cea4000'), ObjectId('6a0567f75ea3054c2cea4001'), ObjectId('6a0567f75ea3054c2cea4002'), ObjectId('6a0567f75ea3054c2cea4003'), ObjectId('6a0567f75ea3054c2cea4004'), ObjectId('6a0567f75ea3054c2cea4005'), ObjectId('6a0567f75ea3054c2cea4006'), ObjectId('6a0567f75ea3054c2cea4007'), ObjectId('6a0567f75ea3054c2cea4008'), ObjectId('6a0567f75ea3054c2cea4009'), ObjectId('6a0567f75ea3054c2cea400a'), ObjectId('6a0567f75ea3054c2cea400b'), ObjectId('6a0567f75ea3054c2cea400c'), ObjectId('6a0567f75ea3054c2cea400d'), ObjectId('6a0567f75ea3054c2cea400e'), ObjectId('6a0567f75ea3054c2cea400f'), ObjectId('6a0567f75ea3054c2cea4010'), ObjectId('6a0567f75ea3054c2cea4011'), ObjectId('6a0567f75ea3054c2cea4012'), ObjectId('6a0567f75ea3054c2cea4013'), ObjectId('6a0567f75ea3054c2cea4014'), ObjectId('6a0567f75ea3054c2cea4015'), ObjectId('6a0567f75ea3054c2cea4016'), ObjectId('6a0567f75ea3054c2cea4017'), ObjectId('6a0567f75ea3054c2cea4018'), ObjectId('6a0567f75ea3054c2cea4019'), ObjectId('6a0567f75ea3054c2cea401a'), ObjectId('6a0567f75ea3054c2cea401b'), ObjectId('6a0567f75ea3054c2cea401c'), ObjectId('6a0567f75ea3054c2cea401d'), ObjectId('6a0567f75ea3054c2cea401e'), ObjectId('6a0567f75ea3054c2cea401f'), ObjectId('6a0567f75ea3054c2cea4020'), ObjectId('6a0567f75ea3054c2cea4021'), ObjectId('6a0567f75ea3054c2cea4022'), ObjectId('6a0567f75ea3054c2cea4023'), ObjectId('6a0567f75ea3054c2cea4024'), ObjectId('6a0567f75ea3054c2cea4025'), ObjectId('6a0567f75ea3054c2cea4026'), ObjectId('6a0567f75ea3054c2cea4027'), ObjectId('6a0567f75ea3054c2cea4028'), ObjectId('6a0567f75ea3054c2cea4029'), ObjectId('6a0567f75ea3054c2cea402a'), ObjectId('6a0567f75ea3054c2cea402b'), ObjectId('6a0567f75ea3054c2cea402c'), ObjectId('6a0567f75ea3054c2cea402d'), ObjectId('6a0567f75ea3054c2cea402e'), ObjectId('6a0567f75ea3054c2cea402f'), ObjectId('6a0567f75ea3054c2cea4030'), ObjectId('6a0567f75ea3054c2cea4031'), ObjectId('6a0567f75ea3054c2cea4032'), ObjectId('6a0567f75ea3054c2cea4033'), ObjectId('6a0567f75ea3054c2cea4034'), ObjectId('6a0567f75ea3054c2cea4035'), ObjectId('6a0567f75ea3054c2cea4036'), ObjectId('6a0567f75ea3054c2cea4037'), ObjectId('6a0567f75ea3054c2cea4038'), ObjectId('6a0567f75ea3054c2cea4039'), ObjectId('6a0567f75ea3054c2cea403a'), ObjectId('6a0567f75ea3054c2cea403b'), ObjectId('6a0567f75ea3054c2cea403c'), ObjectId('6a0567f75ea3054c2cea403d'), ObjectId('6a0567f75ea3054c2cea403e'), ObjectId('6a0567f75ea3054c2cea403f'), ObjectId('6a0567f75ea3054c2cea4040'), ObjectId('6a0567f75ea3054c2cea4041'), ObjectId('6a0567f75ea3054c2cea4042'), ObjectId('6a0567f75ea3054c2cea4043'), ObjectId('6a0567f75ea3054c2cea4044'), ObjectId('6a0567f75ea3054c2cea4045'), ObjectId('6a0567f75ea3054c2cea4046'), ObjectId('6a0567f75ea3054c2cea4047'), ObjectId('6a0567f75ea3054c2cea4048'), ObjectId('6a0567f75ea3054c2cea4049'), ObjectId('6a0567f75ea3054c2cea404a'), ObjectId('6a0567f75ea3054c2cea404b'), ObjectId('6a0567f75ea3054c2cea404c'), ObjectId('6a0567f75ea3054c2cea404d'), ObjectId('6a0567f75ea3054c2cea404e'), ObjectId('6a0567f75ea3054c2cea404f'), ObjectId('6a0567f75ea3054c2cea4050'), ObjectId('6a0567f75ea3054c2cea4051'), ObjectId('6a0567f75ea3054c2cea4052'), ObjectId('6a0567f75ea3054c2cea4053'), ObjectId('6a0567f75ea3054c2cea4054'), ObjectId('6a0567f75ea3054c2cea4055'), ObjectId('6a0567f75ea3054c2cea4056'), ObjectId('6a0567f75ea3054c2cea4057'), ObjectId('6a0567f75ea3054c2cea4058'), ObjectId('6a0567f75ea3054c2cea4059'), ObjectId('6a0567f75ea3054c2cea405a'), ObjectId('6a0567f75ea3054c2cea405b'), ObjectId('6a0567f75ea3054c2cea405c'), ObjectId('6a0567f75ea3054c2cea405d'), ObjectId('6a0567f75ea3054c2cea405e'), ObjectId('6a0567f75ea3054c2cea405f'), ObjectId('6a0567f75ea3054c2cea4060'), ObjectId('6a0567f75ea3054c2cea4061'), ObjectId('6a0567f75ea3054c2cea4062'), ObjectId('6a0567f75ea3054c2cea4063'), ObjectId('6a0567f75ea3054c2cea4064'), ObjectId('6a0567f75ea3054c2cea4065'), ObjectId('6a0567f75ea3054c2cea4066'), ObjectId('6a0567f75ea3054c2cea4067'), ObjectId('6a0567f75ea3054c2cea4068'), ObjectId('6a0567f75ea3054c2cea4069'), ObjectId('6a0567f75ea3054c2cea406a'), ObjectId('6a0567f75ea3054c2cea406b'), ObjectId('6a0567f75ea3054c2cea406c'), ObjectId('6a0567f75ea3054c2cea406d'), ObjectId('6a0567f75ea3054c2cea406e'), ObjectId('6a0567f75ea3054c2cea406f'), ObjectId('6a0567f75ea3054c2cea4070'), ObjectId('6a0567f75ea3054c2cea4071'), ObjectId('6a0567f75ea3054c2cea4072'), ObjectId('6a0567f75ea3054c2cea4073'), ObjectId('6a0567f75ea3054c2cea4074'), ObjectId('6a0567f75ea3054c2cea4075'), ObjectId('6a0567f75ea3054c2cea4076'), ObjectId('6a0567f75ea3054c2cea4077'), ObjectId('6a0567f75ea3054c2cea4078'), ObjectId('6a0567f75ea3054c2cea4079'), ObjectId('6a0567f75ea3054c2cea407a'), ObjectId('6a0567f75ea3054c2cea407b'), ObjectId('6a0567f75ea3054c2cea407c'), ObjectId('6a0567f75ea3054c2cea407d'), ObjectId('6a0567f75ea3054c2cea407e'), ObjectId('6a0567f75ea3054c2cea407f'), ObjectId('6a0567f75ea3054c2cea4080'), ObjectId('6a0567f75ea3054c2cea4081'), ObjectId('6a0567f75ea3054c2cea4082'), ObjectId('6a0567f75ea3054c2cea4083'), ObjectId('6a0567f75ea3054c2cea4084'), ObjectId('6a0567f75ea3054c2cea4085'), ObjectId('6a0567f75ea3054c2cea4086'), ObjectId('6a0567f75ea3054c2cea4087'), ObjectId('6a0567f75ea3054c2cea4088'), ObjectId('6a0567f75ea3054c2cea4089'), ObjectId('6a0567f75ea3054c2cea408a'), ObjectId('6a0567f75ea3054c2cea408b'), ObjectId('6a0567f75ea3054c2cea408c'), ObjectId('6a0567f75ea3054c2cea408d'), ObjectId('6a0567f75ea3054c2cea408e'), ObjectId('6a0567f75ea3054c2cea408f'), ObjectId('6a0567f75ea3054c2cea4090'), ObjectId('6a0567f75ea3054c2cea4091'), ObjectId('6a0567f75ea3054c2cea4092'), ObjectId('6a0567f75ea3054c2cea4093'), ObjectId('6a0567f75ea3054c2cea4094'), ObjectId('6a0567f75ea3054c2cea4095'), ObjectId('6a0567f75ea3054c2cea4096'), ObjectId('6a0567f75ea3054c2cea4097'), ObjectId('6a0567f75ea3054c2cea4098'), ObjectId('6a0567f75ea3054c2cea4099'), ObjectId('6a0567f75ea3054c2cea409a'), ObjectId('6a0567f75ea3054c2cea409b'), ObjectId('6a0567f75ea3054c2cea409c'), ObjectId('6a0567f75ea3054c2cea409d'), ObjectId('6a0567f75ea3054c2cea409e'), ObjectId('6a0567f75ea3054c2cea409f'), ObjectId('6a0567f75ea3054c2cea40a0'), ObjectId('6a0567f75ea3054c2cea40a1'), ObjectId('6a0567f75ea3054c2cea40a2'), ObjectId('6a0567f75ea3054c2cea40

In [48]:
df = pd.read_pickle('./pkl/item_master.pkl')
col = db.get_collection("item_master")
t3 = df.to_dict(orient="records")
col.insert_many(t3)

InsertManyResult([ObjectId('6a0567fa5ea3054c2cea521e'), ObjectId('6a0567fa5ea3054c2cea521f'), ObjectId('6a0567fa5ea3054c2cea5220'), ObjectId('6a0567fa5ea3054c2cea5221'), ObjectId('6a0567fa5ea3054c2cea5222')], acknowledged=True)

In [49]:
df = pd.read_pickle('./pkl/transaction_master.pkl')
col = db.get_collection("transaction_master")
t3 = df.to_dict(orient="records")
col.insert_many(t3)

InsertManyResult([ObjectId('6a0567fc5ea3054c2cea5223'), ObjectId('6a0567fc5ea3054c2cea5224'), ObjectId('6a0567fc5ea3054c2cea5225'), ObjectId('6a0567fc5ea3054c2cea5226'), ObjectId('6a0567fc5ea3054c2cea5227'), ObjectId('6a0567fc5ea3054c2cea5228'), ObjectId('6a0567fc5ea3054c2cea5229'), ObjectId('6a0567fc5ea3054c2cea522a'), ObjectId('6a0567fc5ea3054c2cea522b'), ObjectId('6a0567fc5ea3054c2cea522c'), ObjectId('6a0567fc5ea3054c2cea522d'), ObjectId('6a0567fc5ea3054c2cea522e'), ObjectId('6a0567fc5ea3054c2cea522f'), ObjectId('6a0567fc5ea3054c2cea5230'), ObjectId('6a0567fc5ea3054c2cea5231'), ObjectId('6a0567fc5ea3054c2cea5232'), ObjectId('6a0567fc5ea3054c2cea5233'), ObjectId('6a0567fc5ea3054c2cea5234'), ObjectId('6a0567fc5ea3054c2cea5235'), ObjectId('6a0567fc5ea3054c2cea5236'), ObjectId('6a0567fc5ea3054c2cea5237'), ObjectId('6a0567fc5ea3054c2cea5238'), ObjectId('6a0567fc5ea3054c2cea5239'), ObjectId('6a0567fc5ea3054c2cea523a'), ObjectId('6a0567fc5ea3054c2cea523b'), ObjectId('6a0567fc5ea3054c2cea523c'), ObjectId('6a0567fc5ea3054c2cea523d'), ObjectId('6a0567fc5ea3054c2cea523e'), ObjectId('6a0567fc5ea3054c2cea523f'), ObjectId('6a0567fc5ea3054c2cea5240'), ObjectId('6a0567fc5ea3054c2cea5241'), ObjectId('6a0567fc5ea3054c2cea5242'), ObjectId('6a0567fc5ea3054c2cea5243'), ObjectId('6a0567fc5ea3054c2cea5244'), ObjectId('6a0567fc5ea3054c2cea5245'), ObjectId('6a0567fc5ea3054c2cea5246'), ObjectId('6a0567fc5ea3054c2cea5247'), ObjectId('6a0567fc5ea3054c2cea5248'), ObjectId('6a0567fc5ea3054c2cea5249'), ObjectId('6a0567fc5ea3054c2cea524a'), ObjectId('6a0567fc5ea3054c2cea524b'), ObjectId('6a0567fc5ea3054c2cea524c'), ObjectId('6a0567fc5ea3054c2cea524d'), ObjectId('6a0567fc5ea3054c2cea524e'), ObjectId('6a0567fc5ea3054c2cea524f'), ObjectId('6a0567fc5ea3054c2cea5250'), ObjectId('6a0567fc5ea3054c2cea5251'), ObjectId('6a0567fc5ea3054c2cea5252'), ObjectId('6a0567fc5ea3054c2cea5253'), ObjectId('6a0567fc5ea3054c2cea5254'), ObjectId('6a0567fc5ea3054c2cea5255'), ObjectId('6a0567fc5ea3054c2cea5256'), ObjectId('6a0567fc5ea3054c2cea5257'), ObjectId('6a0567fc5ea3054c2cea5258'), ObjectId('6a0567fc5ea3054c2cea5259'), ObjectId('6a0567fc5ea3054c2cea525a'), ObjectId('6a0567fc5ea3054c2cea525b'), ObjectId('6a0567fc5ea3054c2cea525c'), ObjectId('6a0567fc5ea3054c2cea525d'), ObjectId('6a0567fc5ea3054c2cea525e'), ObjectId('6a0567fc5ea3054c2cea525f'), ObjectId('6a0567fc5ea3054c2cea5260'), ObjectId('6a0567fc5ea3054c2cea5261'), ObjectId('6a0567fc5ea3054c2cea5262'), ObjectId('6a0567fc5ea3054c2cea5263'), ObjectId('6a0567fc5ea3054c2cea5264'), ObjectId('6a0567fc5ea3054c2cea5265'), ObjectId('6a0567fc5ea3054c2cea5266'), ObjectId('6a0567fc5ea3054c2cea5267'), ObjectId('6a0567fc5ea3054c2cea5268'), ObjectId('6a0567fc5ea3054c2cea5269'), ObjectId('6a0567fc5ea3054c2cea526a'), ObjectId('6a0567fc5ea3054c2cea526b'), ObjectId('6a0567fc5ea3054c2cea526c'), ObjectId('6a0567fc5ea3054c2cea526d'), ObjectId('6a0567fc5ea3054c2cea526e'), ObjectId('6a0567fc5ea3054c2cea526f'), ObjectId('6a0567fc5ea3054c2cea5270'), ObjectId('6a0567fc5ea3054c2cea5271'), ObjectId('6a0567fc5ea3054c2cea5272'), ObjectId('6a0567fc5ea3054c2cea5273'), ObjectId('6a0567fc5ea3054c2cea5274'), ObjectId('6a0567fc5ea3054c2cea5275'), ObjectId('6a0567fc5ea3054c2cea5276'), ObjectId('6a0567fc5ea3054c2cea5277'), ObjectId('6a0567fc5ea3054c2cea5278'), ObjectId('6a0567fc5ea3054c2cea5279'), ObjectId('6a0567fc5ea3054c2cea527a'), ObjectId('6a0567fc5ea3054c2cea527b'), ObjectId('6a0567fc5ea3054c2cea527c'), ObjectId('6a0567fc5ea3054c2cea527d'), ObjectId('6a0567fc5ea3054c2cea527e'), ObjectId('6a0567fc5ea3054c2cea527f'), ObjectId('6a0567fc5ea3054c2cea5280'), ObjectId('6a0567fc5ea3054c2cea5281'), ObjectId('6a0567fc5ea3054c2cea5282'), ObjectId('6a0567fc5ea3054c2cea5283'), ObjectId('6a0567fc5ea3054c2cea5284'), ObjectId('6a0567fc5ea3054c2cea5285'), ObjectId('6a0567fc5ea3054c2cea5286'), ObjectId('6a0567fc5ea3054c2cea5287'), ObjectId('6a0567fc5ea3054c2cea5288'), ObjectId('6a0567fc5ea3054c2cea5289'), ObjectId('6a0567fc5ea3054c2cea528a'), ObjectId('6a0567fc5ea3054c2cea528b'), ObjectId('6a0567fc5ea3054c2cea528c'), ObjectId('6a0567fc5ea3054c2cea528d'), ObjectId('6a0567fc5ea3054c2cea528e'), ObjectId('6a0567fc5ea3054c2cea528f'), ObjectId('6a0567fc5ea3054c2cea5290'), ObjectId('6a0567fc5ea3054c2cea5291'), ObjectId('6a0567fc5ea3054c2cea5292'), ObjectId('6a0567fc5ea3054c2cea5293'), ObjectId('6a0567fc5ea3054c2cea5294'), ObjectId('6a0567fc5ea3054c2cea5295'), ObjectId('6a0567fc5ea3054c2cea5296'), ObjectId('6a0567fc5ea3054c2cea5297'), ObjectId('6a0567fc5ea3054c2cea5298'), ObjectId('6a0567fc5ea3054c2cea5299'), ObjectId('6a0567fc5ea3054c2cea529a'), ObjectId('6a0567fc5ea3054c2cea529b'), ObjectId('6a0567fc5ea3054c2cea529c'), ObjectId('6a0567fc5ea3054c2cea529d'), ObjectId('6a0567fc5ea3054c2cea529e'), ObjectId('6a0567fc5ea3054c2cea529f'), ObjectId('6a0567fc5ea3054c2cea52a0'), ObjectId('6a0567fc5ea3054c2cea52a1'), ObjectId('6a0567fc5ea3054c2cea52a2'), ObjectId('6a0567fc5ea3054c2cea52a3'), ObjectId('6a0567fc5ea3054c2cea52a4'), ObjectId('6a0567fc5ea3054c2cea52a5'), ObjectId('6a0567fc5ea3054c2cea52a6'), ObjectId('6a0567fc5ea3054c2cea52a7'), ObjectId('6a0567fc5ea3054c2cea52a8'), ObjectId('6a0567fc5ea3054c2cea52a9'), ObjectId('6a0567fc5ea3054c2cea52aa'), ObjectId('6a0567fc5ea3054c2cea52ab'), ObjectId('6a0567fc5ea3054c2cea52ac'), ObjectId('6a0567fc5ea3054c2cea52ad'), ObjectId('6a0567fc5ea3054c2cea52ae'), ObjectId('6a0567fc5ea3054c2cea52af'), ObjectId('6a0567fc5ea3054c2cea52b0'), ObjectId('6a0567fc5ea3054c2cea52b1'), ObjectId('6a0567fc5ea3054c2cea52b2'), ObjectId('6a0567fc5ea3054c2cea52b3'), ObjectId('6a0567fc5ea3054c2cea52b4'), ObjectId('6a0567fc5ea3054c2cea52b5'), ObjectId('6a0567fc5ea3054c2cea52b6'), ObjectId('6a0567fc5ea3054c2cea52b7'), ObjectId('6a0567fc5ea3054c2cea52b8'), ObjectId('6a0567fc5ea3054c2cea52b9'), ObjectId('6a0567fc5ea3054c2cea52ba'), ObjectId('6a0567fc5ea3054c2cea52bb'), ObjectId('6a0567fc5ea3054c2cea52bc'), ObjectId('6a0567fc5ea3054c2cea52bd'), ObjectId('6a0567fc5ea3054c2cea52be'), ObjectId('6a0567fc5ea3054c2cea52bf'), ObjectId('6a0567fc5ea3054c2cea52c0'), ObjectId('6a0567fc5ea3054c2cea52c1'), ObjectId('6a0567fc5ea3054c2cea52c2'), ObjectId('6a0567fc5ea3054c2cea52c3'), ObjectId('6a0567fc5ea3054c2cea52c4'), ObjectId('6a0567fc5ea3054c2cea52c5'), ObjectId('6a0567fc5ea3054c2cea52c6'), ObjectId('6a0567fc5ea3054c2cea52c7'), ObjectId('6a0567fc5ea3054c2cea52c8'), ObjectId('6a0567fc5ea3054c2cea52c9'), ObjectId('6a0567fc5ea3054c2cea52ca'), ObjectId('6a0567fc5ea3054c2cea52cb'), ObjectId('6a0567fc5ea3054c2cea52cc'), ObjectId('6a0567fc5ea3054c2cea52cd'), ObjectId('6a0567fc5ea3054c2cea52ce'), ObjectId('6a0567fc5ea3054c2cea52cf'), ObjectId('6a0567fc5ea3054c2cea52d0'), ObjectId('6a0567fc5ea3054c2cea52d1'), ObjectId('6a0567fc5ea3054c2cea52d2'), ObjectId('6a0567fc5ea3054c2cea52d3'), ObjectId('6a0567fc5ea3054c2cea52d4'), ObjectId('6a0567fc5ea3054c2cea52d5'), ObjectId('6a0567fc5ea3054c2cea52d6'), ObjectId('6a0567fc5ea3054c2cea52d7'), ObjectId('6a0567fc5ea3054c2cea52d8'), ObjectId('6a0567fc5ea3054c2cea52d9'), ObjectId('6a0567fc5ea3054c2cea52da'), ObjectId('6a0567fc5ea3054c2cea52db'), ObjectId('6a0567fc5ea3054c2cea52dc'), ObjectId('6a0567fc5ea3054c2cea52dd'), ObjectId('6a0567fc5ea3054c2cea52de'), ObjectId('6a0567fc5ea3054c2cea52df'), ObjectId('6a0567fc5ea3054c2cea52e0'), ObjectId('6a0567fc5ea3054c2cea52e1'), ObjectId('6a0567fc5ea3054c2cea52e2'), ObjectId('6a0567fc5ea3054c2cea52e3'), ObjectId('6a0567fc5ea3054c2cea52e4'), ObjectId('6a0567fc5ea3054c2cea52e5'), ObjectId('6a0567fc5ea3054c2cea52e6'), ObjectId('6a0567fc5ea3054c2cea52e7'), ObjectId('6a0567fc5ea3054c2cea52e8'), ObjectId('6a0567fc5ea3054c2cea52e9'), ObjectId('6a0567fc5ea3054c2cea52ea'), ObjectId('6a0567fc5ea3054c2cea52eb'), ObjectId('6a0567fc5ea3054c2cea52ec'), ObjectId('6a0567fc5ea3054c2cea52ed'), ObjectId('6a0567fc5ea3054c2cea52ee'), ObjectId('6a0567fc5ea3054c2cea52ef'), ObjectId('6a0567fc5ea3054c2cea52f0'), ObjectId('6a0567fc5ea3054c2cea52f1'), ObjectId('6a0567fc5ea3054c2cea52f2'), ObjectId('6a0567fc5ea3054c2cea52f3'), ObjectId('6a0567fc5ea3054c2cea52f4'), ObjectId('6a0567fc5ea3054c2cea52f5'), ObjectId('6a0567fc5ea3054c2cea52f6'), ObjectId('6a0567fc5ea3054c2cea52f7'), ObjectId('6a0567fc5ea3054c2cea52f8'), ObjectId('6a0567fc5ea3054c2cea52f9'), ObjectId('6a0567fc5ea3054c2cea52fa'), ObjectId('6a0567fc5ea3054c2cea52fb'), ObjectId('6a0567fc5ea3054c2cea52fc'), ObjectId('6a0567fc5ea3054c2cea52fd'), ObjectId('6a0567fc5ea3054c2cea52fe'), ObjectId('6a0567fc5ea3054c2cea52ff'), ObjectId('6a0567fc5ea3054c2cea5300'), ObjectId('6a0567fc5ea3054c2cea5301'), ObjectId('6a0567fc5ea3054c2cea5302'), ObjectId('6a0567fc5ea3054c2cea5303'), ObjectId('6a0567fc5ea3054c2cea5304'), ObjectId('6a0567fc5ea3054c2cea5305'), ObjectId('6a0567fc5ea3054c2cea5306'), ObjectId('6a0567fc5ea3054c2cea5307'), ObjectId('6a0567fc5ea3054c2cea5308'), ObjectId('6a0567fc5ea3054c2cea5309'), ObjectId('6a0567fc5ea3054c2cea530a'), ObjectId('6a0567fc5ea3054c2cea530b'), ObjectId('6a0567fc5ea3054c2cea530c'), ObjectId('6a0567fc5ea3054c2cea530d'), ObjectId('6a0567fc5ea3054c2cea530e'), ObjectId('6a0567fc5ea3054c2cea530f'), ObjectId('6a0567fc5ea3054c2cea5310'), ObjectId('6a0567fc5ea3054c2cea5311'), ObjectId('6a0567fc5ea3054c2cea5312'), ObjectId('6a0567fc5ea3054c2cea5313'), ObjectId('6a0567fc5ea3054c2cea5314'), ObjectId('6a0567fc5ea3054c2cea5315'), ObjectId('6a0567fc5ea3054c2cea5316'), ObjectId('6a0567fc5ea3054c2cea5317'), ObjectId('6a0567fc5ea3054c2cea5318'), ObjectId('6a0567fc5ea3054c2cea5319'), ObjectId('6a0567fc5ea3054c2cea531a'), ObjectId('6a0567fc5ea3054c2cea531b'), ObjectId('6a0567fc5ea3054c2cea531c'), ObjectId('6a0567fc5ea3054c2cea531d'), ObjectId('6a0567fc5ea3054c2cea531e'), ObjectId('6a0567fc5ea3054c2cea531f'), ObjectId('6a0567fc5ea3054c2cea5320'), ObjectId('6a0567fc5ea3054c2cea5321'), ObjectId('6a0567fc5ea3054c2cea5322'), ObjectId('6a0567fc5ea3054c2cea5323'), ObjectId('6a0567fc5ea3054c2cea5324'), ObjectId('6a0567fc5ea3054c2cea5325'), ObjectId('6a0567fc5ea3054c2cea5326'), ObjectId('6a0567fc5ea3054c2cea5327'), ObjectId('6a0567fc5ea3054c2cea5328'), ObjectId('6a0567fc5ea3054c2cea5329'), ObjectId('6a0567fc5ea3054c2cea532a'), ObjectId('6a0567fc5ea3054c2cea532b'), ObjectId('6a0567fc5ea3054c2cea532c'), ObjectId('6a0567fc5ea3054c2cea532d'), ObjectId('6a0567fc5ea3054c2cea532e'), ObjectId('6a0567fc5ea3054c2cea532f'), ObjectId('6a0567fc5ea3054c2cea5330'), ObjectId('6a0567fc5ea3054c2cea5331'), ObjectId('6a0567fc5ea3054c2cea5332'), ObjectId('6a0567fc5ea3054c2cea5333'), ObjectId('6a0567fc5ea3054c2cea5334'), ObjectId('6a0567fc5ea3054c2cea5335'), ObjectId('6a0567fc5ea3054c2cea5336'), ObjectId('6a0567fc5ea3054c2cea5337'), ObjectId('6a0567fc5ea3054c2cea5338'), ObjectId('6a0567fc5ea3054c2cea5339'), ObjectId('6a0567fc5ea3054c2cea533a'), ObjectId('6a0567fc5ea3054c2cea533b'), ObjectId('6a0567fc5ea3054c2cea533c'), ObjectId('6a0567fc5ea3054c2cea533d'), ObjectId('6a0567fc5ea3054c2cea533e'), ObjectId('6a0567fc5ea3054c2cea533f'), ObjectId('6a0567fc5ea3054c2cea5340'), ObjectId('6a0567fc5ea3054c2cea5341'), ObjectId('6a0567fc5ea3054c2cea5342'), ObjectId('6a0567fc5ea3054c2cea5343'), ObjectId('6a0567fc5ea3054c2cea5344'), ObjectId('6a0567fc5ea3054c2cea5345'), ObjectId('6a0567fc5ea3054c2cea5346'), ObjectId('6a0567fc5ea3054c2cea5347'), ObjectId('6a0567fc5ea3054c2cea5348'), ObjectId('6a0567fc5ea3054c2cea5349'), ObjectId('6a0567fc5ea3054c2cea534a'), ObjectId('6a0567fc5ea3054c2cea534b'), ObjectId('6a0567fc5ea3054c2cea534c'), ObjectId('6a0567fc5ea3054c2cea534d'), ObjectId('6a0567fc5ea3054c2cea534e'), ObjectId('6a0567fc5ea3054c2cea534f'), ObjectId('6a0567fc5ea3054c2cea5350'), ObjectId('6a0567fc5ea3054c2cea5351'), ObjectId('6a0567fc5ea3054c2cea5352'), ObjectId('6a0567fc5ea3054c2cea5353'), ObjectId('6a0567fc5ea3054c2cea5354'), ObjectId('6a0567fc5ea3054c2cea5355'), ObjectId('6a0567fc5ea3054c2cea5356'), ObjectId('6a0567fc5ea3054c2cea5357'), ObjectId('6a0567fc5ea3054c2cea5358'), ObjectId('6a0567fc5ea3054c2cea5359'), ObjectId('6a0567fc5ea3054c2cea535a'), ObjectId('6a0567fc5ea3054c2cea535b'), ObjectId('6a0567fc5ea3054c2cea535c'), ObjectId('6a0567fc5ea3054c2cea535d'), ObjectId('6a0567fc5ea3054c2cea535e'), ObjectId('6a0567fc5ea3054c2cea535f'), ObjectId('6a0567fc5ea3054c2cea5360'), ObjectId('6a0567fc5ea3054c2cea5361'), ObjectId('6a0567fc5ea3054c2cea5362'), ObjectId('6a0567fc5ea3054c2cea5363'), ObjectId('6a0567fc5ea3054c2cea5364'), ObjectId('6a0567fc5ea3054c2cea5365'), ObjectId('6a0567fc5ea3054c2cea5366'), ObjectId('6a0567fc5ea3054c2cea5367'), ObjectId('6a0567fc5ea3054c2cea5368'), ObjectId('6a0567fc5ea3054c2cea5369'), ObjectId('6a0567fc5ea3054c2cea536a'), ObjectId('6a0567fc5ea3054c2cea536b'), ObjectId('6a0567fc5ea3054c2cea536c'), ObjectId('6a0567fc5ea3054c2cea536d'), ObjectId('6a0567fc5ea3054c2cea536e'), ObjectId('6a0567fc5ea3054c2cea536f'), ObjectId('6a0567fc5ea3054c2cea5370'), ObjectId('6a0567fc5ea3054c2cea5371'), ObjectId('6a0567fc5ea3054c2cea5372'), ObjectId('6a0567fc5ea3054c2cea5373'), ObjectId('6a0567fc5ea3054c2cea5374'), ObjectId('6a0567fc5ea3054c2cea5375'), ObjectId('6a0567fc5ea3054c2cea5376'), ObjectId('6a0567fc5ea3054c2cea5377'), ObjectId('6a0567fc5ea3054c2cea5378'), ObjectId('6a0567fc5ea3054c2cea5379'), ObjectId('6a0567fc5ea3054c2cea537a'), ObjectId('6a0567fc5ea3054c2cea537b'), ObjectId('6a0567fc5ea3054c2cea537c'), ObjectId('6a0567fc5ea3054c2cea537d'), ObjectId('6a0567fc5ea3054c2cea537e'), ObjectId('6a0567fc5ea3054c2cea537f'), ObjectId('6a0567fc5ea3054c2cea5380'), ObjectId('6a0567fc5ea3054c2cea5381'), ObjectId('6a0567fc5ea3054c2cea5382'), ObjectId('6a0567fc5ea3054c2cea5383'), ObjectId('6a0567fc5ea3054c2cea5384'), ObjectId('6a0567fc5ea3054c2cea5385'), ObjectId('6a0567fc5ea3054c2cea5386'), ObjectId('6a0567fc5ea3054c2cea5387'), ObjectId('6a0567fc5ea3054c2cea5388'), ObjectId('6a0567fc5ea3054c2cea5389'), ObjectId('6a0567fc5ea3054c2cea538a'), ObjectId('6a0567fc5ea3054c2cea538b'), ObjectId('6a0567fc5ea3054c2cea538c'), ObjectId('6a0567fc5ea3054c2cea538d'), ObjectId('6a0567fc5ea3054c2cea538e'), ObjectId('6a0567fc5ea3054c2cea538f'), ObjectId('6a0567fc5ea3054c2cea5390'), ObjectId('6a0567fc5ea3054c2cea5391'), ObjectId('6a0567fc5ea3054c2cea5392'), ObjectId('6a0567fc5ea3054c2cea5393'), ObjectId('6a0567fc5ea3054c2cea5394'), ObjectId('6a0567fc5ea3054c2cea5395'), ObjectId('6a0567fc5ea3054c2cea5396'), ObjectId('6a0567fc5ea3054c2cea5397'), ObjectId('6a0567fc5ea3054c2cea5398'), ObjectId('6a0567fc5ea3054c2cea5399'), ObjectId('6a0567fc5ea3054c2cea539a'), ObjectId('6a0567fc5ea3054c2cea539b'), ObjectId('6a0567fc5ea3054c2cea539c'), ObjectId('6a0567fc5ea3054c2cea539d'), ObjectId('6a0567fc5ea3054c2cea539e'), ObjectId('6a0567fc5ea3054c2cea539f'), ObjectId('6a0567fc5ea3054c2cea53a0'), ObjectId('6a0567fc5ea3054c2cea53a1'), ObjectId('6a0567fc5ea3054c2cea53a2'), ObjectId('6a0567fc5ea3054c2cea53a3'), ObjectId('6a0567fc5ea3054c2cea53a4'), ObjectId('6a0567fc5ea3054c2cea53a5'), ObjectId('6a0567fc5ea3054c2cea53a6'), ObjectId('6a0567fc5ea3054c2cea53a7'), ObjectId('6a0567fc5ea3054c2cea53a8'), ObjectId('6a0567fc5ea3054c2cea53a9'), ObjectId('6a0567fc5ea3054c2cea53aa'), ObjectId('6a0567fc5ea3054c2cea53ab'), ObjectId('6a0567fc5ea3054c2cea53ac'), ObjectId('6a0567fc5ea3054c2cea53ad'), ObjectId('6a0567fc5ea3054c2cea53ae'), ObjectId('6a0567fc5ea3054c2cea53af'), ObjectId('6a0567fc5ea3054c2cea53b0'), ObjectId('6a0567fc5ea3054c2cea53b1'), ObjectId('6a0567fc5ea3054c2cea53b2'), ObjectId('6a0567fc5ea3054c2cea53b3'), ObjectId('6a0567fc5ea3054c2cea53b4'), ObjectId('6a0567fc5ea3054c2cea53b5'), ObjectId('6a0567fc5ea3054c2cea53b6'), ObjectId('6a0567fc5ea3054c2cea53b7'), ObjectId('6a0567fc5ea3054c2cea53b8'), ObjectId('6a0567fc5ea3054c2cea53b9'), ObjectId('6a0567fc5ea3054c2cea53ba'), ObjectId('6a0567fc5ea3054c2cea53bb'), ObjectId('6a0567fc5ea3054c2cea53bc'), ObjectId('6a0567fc5ea3054c2cea53bd'), ObjectId('6a0567fc5ea3054c2cea53be'), ObjectId('6a0567fc5ea3054c2cea53bf'), ObjectId('6a0567fc5ea3054c2cea53c0'), ObjectId('6a0567fc5ea3054c2cea53c1'), ObjectId('6a0567fc5ea3054c2cea53c2'), ObjectId('6a0567fc5ea3054c2cea53c3'), ObjectId('6a0567fc5ea3054c2cea53c4'), ObjectId('6a0567fc5ea3054c2cea53c5'), ObjectId('6a0567fc5ea3054c2cea53c6'), ObjectId('6a0567fc5ea3054c2cea53c7'), ObjectId('6a0567fc5ea3054c2cea53c8'), ObjectId('6a0567fc5ea3054c2cea53c9'), ObjectId('6a0567fc5ea3054c2cea53ca'), ObjectId('6a0567fc5ea3054c2cea53cb'), ObjectId('6a0567fc5ea3054c2cea53cc'), ObjectId('6a0567fc5ea3054c2cea53cd'), ObjectId('6a0567fc5ea3054c2cea53ce'), ObjectId('6a0567fc5ea3054c2cea53cf'), ObjectId('6a0567fc5ea3054c2cea53d0'), ObjectId('6a0567fc5ea3054c2cea53d1'), ObjectId('6a0567fc5ea3054c2cea53d2'), ObjectId('6a0567fc5ea3054c2cea53d3'), ObjectId('6a0567fc5ea3054c2cea53d4'), ObjectId('6a0567fc5ea3054c2cea53d5'), ObjectId('6a0567fc5ea3054c2cea53d6'), ObjectId('6a0567fc5ea3054c2cea53d7'), ObjectId('6a0567fc5ea3054c2cea53d8'), ObjectId('6a0567fc5ea3054c2cea53d9'), ObjectId('6a0567fc5ea3054c2cea53da'), ObjectId('6a0567fc5ea3054c2cea53db'), ObjectId('6a0567fc5ea3054c2cea53dc'), ObjectId('6a0567fc5ea3054c2cea53dd'), ObjectId('6a0567fc5ea3054c2cea53de'), ObjectId('6a0567fc5ea3054c2cea53df'), ObjectId('6a0567fc5ea3054c2cea53e0'), ObjectId('6a0567fc5ea3054c2cea53e1'), ObjectId('6a0567fc5ea3054c2cea53e2'), ObjectId('6a0567fc5ea3054c2cea53e3'), ObjectId('6a0567fc5ea3054c2cea53e4'), ObjectId('6a0567fc5ea3054c2cea53e5'), ObjectId('6a0567fc5ea3054c2cea53e6'), ObjectId('6a0567fc5ea3054c2cea53e7'), ObjectId('6a0567fc5ea3054c2cea53e8'), ObjectId('6a0567fc5ea3054c2cea53e9'), ObjectId('6a0567fc5ea3054c2cea53ea'), ObjectId('6a0567fc5ea3054c2cea53eb'), ObjectId('6a0567fc5ea3054c2cea53ec'), ObjectId('6a0567fc5ea3054c2cea53ed'), ObjectId('6a0567fc5ea3054c2cea53ee'), ObjectId('6a0567fc5ea3054c2cea53ef'), ObjectId('6a0567fc5ea3054c2cea53f0'), ObjectId('6a0567fc5ea3054c2cea53f1'), ObjectId('6a0567fc5ea3054c2cea53f2'), ObjectId('6a0567fc5ea3054c2cea53f3'), ObjectId('6a0567fc5ea3054c2cea53f4'), ObjectId('6a0567fc5ea3054c2cea53f5'), ObjectId('6a0567fc5ea3054c2cea53f6'), ObjectId('6a0567fc5ea3054c2cea53f7'), ObjectId('6a0567fc5ea3054c2cea53f8'), ObjectId('6a0567fc5ea3054c2cea53f9'), ObjectId('6a0567fc5ea3054c2cea53fa'), ObjectId('6a0567fc5ea3054c2cea53fb'), ObjectId('6a0567fc5ea3054c2cea53fc'), ObjectId('6a0567fc5ea3054c2cea53fd'), ObjectId('6a0567fc5ea3054c2cea53fe'), ObjectId('6a0567fc5ea3054c2cea53ff'), ObjectId('6a0567fc5ea3054c2cea5400'), ObjectId('6a0567fc5ea3054c2cea5401'), ObjectId('6a0567fc5ea3054c2cea5402'), ObjectId('6a0567fc5ea3054c2cea5403'), ObjectId('6a0567fc5ea3054c2cea5404'), ObjectId('6a0567fc5ea3054c2cea5405'), ObjectId('6a0567fc5ea3054c2cea5406'), ObjectId('6a0567fc5ea3054c2cea5407'), ObjectId('6a0567fc5ea3054c2cea5408'), ObjectId('6a0567fc5ea3054c2cea5409'), ObjectId('6a0567fc5ea3054c2cea540a'), ObjectId('6a0567fc5ea3054c2cea540b'), ObjectId('6a0567fc5ea3054c2cea540c'), ObjectId('6a0567fc5ea3054c2cea540d'), ObjectId('6a0567fc5ea3054c2cea540e'), ObjectId('6a0567fc5ea3054c2cea540f'), ObjectId('6a0567fc5ea3054c2cea5410'), ObjectId('6a0567fc5ea3054c2cea5411'), ObjectId('6a0567fc5ea3054c2cea5412'), ObjectId('6a0567fc5ea3054c2cea5413'), ObjectId('6a0567fc5ea3054c2cea5414'), ObjectId('6a0567fc5ea3054c2cea5415'), ObjectId('6a0567fc5ea3054c2cea5416'), ObjectId('6a0567fc5ea3054c2cea5417'), ObjectId('6a0567fc5ea3054c2cea5418'), ObjectId('6a0567fc5ea3054c2cea5419'), ObjectId('6a0567fc5ea3054c2cea541a'), ObjectId('6a0567fc5ea3054c2cea541b'), ObjectId('6a0567fc5ea3054c2cea541c'), ObjectId('6a0567fc5ea3054c2cea541d'), ObjectId('6a0567fc5ea3054c2cea541e'), ObjectId('6a0567fc5ea3054c2cea541f'), ObjectId('6a0567fc5ea3054c2cea5420'), ObjectId('6a0567fc5ea3054c2cea5421'), ObjectId('6a0567fc5ea3054c2cea5422'), ObjectId('6a0567fc5ea3054c2cea5423'), ObjectId('6a0567fc5ea3054c2cea5424'), ObjectId('6a0567fc5ea3054c2cea5425'), ObjectId('6a0567fc5ea3054c2cea5426'), ObjectId('6a0567fc5ea3054c2cea5427'), ObjectId('6a0567fc5ea3054c2cea5428'), ObjectId('6a0567fc5ea3054c2cea5429'), ObjectId('6a0567fc5ea3054c2cea542a'), ObjectId('6a0567fc5ea3054c2cea542b'), ObjectId('6a0567fc5ea3054c2cea542c'), ObjectId('6a0567fc5ea3054c2cea542d'), ObjectId('6a0567fc5ea3054c2cea542e'), ObjectId('6a0567fc5ea3054c2cea542f'), ObjectId('6a0567fc5ea3054c2cea54

In [50]:
import pandas as pd
# 가져올 컬렉션 선택
c1 = db.get_collection("customer_master")
c2 = db.get_collection("item_master")
c3 = db.get_collection("transaction_master")
# 전체 데이터를 가져오는데 _id 정보는 제거해서
d1 = c1.find({}, {"_id":0})
d2 = c2.find({}, {"_id":0})
d3 = c3.find({}, {"_id":0})
# 가져온 데이터를 dataframe으로 변경
customer = pd.DataFrame(list(d1))
item = pd.DataFrame(list(d2))
transaction = pd.DataFrame(list(d3))

In [51]:
customer

,고객아이디,고객명,등록일,이메일,성별,나이,생년월일,지역,년,월,일,연령대
0,IK152942,김서준,2019-01-01 00:25:00,hirata_yuujirou@example.com,M,37,1990-06-10,대전광역시,1990,6,10,30대
1,TS808488,김예준,2019-01-01 01:13:00,tamura_shiori@example.com,F,41,1986-05-20,인천광역시,1986,5,20,40대
2,AS834628,김도윤,2019-01-01 02:00:00,hisano_yuki@example.com,F,71,1956-01-02,광주광역시,1956,1,2,70대
3,AS345469,김시우,2019-01-01 04:48:00,tsuruoka_kaoru@example.com,M,82,1945-03-25,인천광역시,1945,3,25,초고령
4,GD892565,김주원,2019-01-01 04:54:00,oouchi_takashi@example.com,M,62,1965-08-05,울산광역시,1965,8,5,60대
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,AS677229,정우석,2019-07-31 16:52:00,hirayama_risa@example.com,F,86,1941-10-17,대전광역시,1941,10,17,초고령
4996,HD758694,정영훈,2019-07-31 19:09:00,nakahara_mahiru@example.com,F,36,1991-11-13,광주광역시,1991,11,13,30대
4997,PL538517,정준기,2019-07-31 19:30:00,tabata_yuu1@example.com,F,82,1945-12-28,대전광역시,1945,12,28,초고령
4998,OA955088,정도형,2019-07-31 22:32:00,setouchi_hikaru@example.com,F,83,1944-04-09,부산광역시,1944,4,9,초고령
4999,HI349563,정지석,2019-07-31 22:49:00,horii_kanji@example.com,M,29,1998-02-06,서울특별시,1998,2,6,20대

In [52]:
item

   물품코드   물품명    물품가격
0  S001  PC-A   50000
1  S002  PC-B   85000
2  S003  PC-C  120000
3  S004  PC-D  180000
4  S005  PC-E  210000

In [53]:
transaction

             거래코드    결제금액                 결제일     고객아이디
0     T0000000113  210000 2019-02-01 01:36:57  PL563502
1     T0000000114   50000 2019-02-01 01:37:23  HD678019
2     T0000000115  120000 2019-02-01 02:34:19  HD298120
3     T0000000116  210000 2019-02-01 02:47:23  IK452215
4     T0000000117  170000 2019-02-01 04:33:46  PL542865
...           ...     ...                 ...       ...
6781  T0000006894  180000 2019-07-31 21:20:44  HI400734
6782  T0000006895   85000 2019-07-31 21:52:48  AS339451
6783  T0000006896  100000 2019-07-31 23:35:25  OA027325
6784  T0000006897   85000 2019-07-31 23:39:35  TS624738
6785  T0000006898   85000 2019-07-31 23:41:38  AS834214

[6786 rows x 4 columns]

In [ ]:
# 5000
customer.info()

In [ ]:
# 5개의 물품
item.info()

In [ ]:
# 6786개 거래내역
transaction.info()

In [54]:
transaction_d1 = pd.read_csv('http://114.207.245.181:13000/csv/transaction_detail_1.csv')
transaction_d2 = pd.read_csv('http://114.207.245.181:13000/csv/transaction_detail_2.csv')

In [55]:
transaction_d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   object
 2   item_id         5000 non-null   object
 3   quantity        5000 non-null   int64
dtypes: int64(2), object(2)
memory usage: 156.4+ KB

In [56]:
transaction_d2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   object
 2   item_id         2144 non-null   object
 3   quantity        2144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 67.1+ KB

In [57]:
transaction_detail = pd.concat([transaction_d1, transaction_d2], ignore_index=True)
transaction_detail.info()
transaction_detail.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   object
 2   item_id         7144 non-null   object
 3   quantity        7144 non-null   int64
dtypes: int64(2), object(2)
memory usage: 223.4+ KB

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1
1          1    T0000000114    S001         1
2          2    T0000000115    S003         1

In [58]:
transaction_detail.columns

Index(['detail_id', 'transaction_id', 'item_id', 'quantity'], dtype='object')

In [59]:
t1 = {'detail_id':'거래번호', 'transaction_id':'거래코드',
        'item_id':'물품코드', 'quantity':'수량'}

transaction_detail = transaction_detail.rename(columns=t1)
transaction_detail

      거래번호         거래코드  물품코드  수량
0        0  T0000000113  S005   1
1        1  T0000000114  S001   1
2        2  T0000000115  S003   1
3        3  T0000000116  S005   1
4        4  T0000000117  S002   2
...    ...          ...   ...  ..
7139  7139  T0000006894  S004   1
7140  7140  T0000006895  S002   1
7141  7141  T0000006896  S001   2
7142  7142  T0000006897  S002   1
7143  7143  T0000006898  S002   1

[7144 rows x 4 columns]

In [60]:
# 6786개 거래내역, 7144개 거래내역상세
# 에시) 중국집 54000, 짜장1, 짬뽕2
transaction, transaction_detail

(             거래코드    결제금액                 결제일     고객아이디
 0     T0000000113  210000 2019-02-01 01:36:57  PL563502
 1     T0000000114   50000 2019-02-01 01:37:23  HD678019
 2     T0000000115  120000 2019-02-01 02:34:19  HD298120
 3     T0000000116  210000 2019-02-01 02:47:23  IK452215
 4     T0000000117  170000 2019-02-01 04:33:46  PL542865
 ...           ...     ...                 ...       ...
 6781  T0000006894  180000 2019-07-31 21:20:44  HI400734
 6782  T0000006895   85000 2019-07-31 21:52:48  AS339451
 6783  T0000006896  100000 2019-07-31 23:35:25  OA027325
 6784  T0000006897   85000 2019-07-31 23:39:35  TS624738
 6785  T0000006898   85000 2019-07-31 23:41:38  AS834214

 [6786 rows x 4 columns],
       거래번호         거래코드  물품코드  수량
 0        0  T0000000113  S005   1
 1        1  T0000000114  S001   1
 2        2  T0000000115  S003   1
 3        3  T0000000116  S005   1
 4        4  T0000000117  S002   2
 ...    ...          ...   ...  ..
 7139  7139  T0000006894  S004   1
 7140  7140  T0000006895  S002   1
 7141  7141  T0000006896  S001   2
 7142  7142  T0000006897  S002   1
 7143  7143  T0000006898  S002   1

 [7144 rows x 4 columns])

In [61]:
# 거래코드가 중복인 항목 표시
transaction_detail[transaction_detail['거래코드'].duplicated(keep=False)]

      거래번호         거래코드  물품코드  수량
81      81  T0000000194  S002   1
82      82  T0000000194  S005   1
96      96  T0000000208  S003   1
97      97  T0000000208  S001   1
108    108  T0000000219  S003   1
...    ...          ...   ...  ..
7072  7072  T0000006829  S003   1
7107  7107  T0000006864  S001   1
7108  7108  T0000006864  S001   1
7128  7128  T0000006884  S001   1
7129  7129  T0000006884  S005   1

[697 rows x 4 columns]

In [62]:
# 거래내역 결제금액 합계
sum(transaction['결제금액'])

971135000

In [63]:
transaction[['거래코드', '결제일', '고객아이디']].head(1)

          거래코드                 결제일     고객아이디
0  T0000000113 2019-02-01 01:36:57  PL563502

In [64]:
transaction_detail[['거래코드', '물품코드', '수량']].head(1)

          거래코드  물품코드  수량
0  T0000000113  S005   1

In [65]:
transaction_data = pd.merge(
    transaction[['거래코드', '결제일', '고객아이디']],
    transaction_detail[['거래코드', '물품코드', '수량']],
    on="거래코드",
    how="right"
)
transaction_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   거래코드    7144 non-null   object
 1   결제일     7144 non-null   datetime64[ns]
 2   고객아이디   7144 non-null   object
 3   물품코드    7144 non-null   object
 4   수량      7144 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 279.2+ KB

In [66]:
transaction_data.head(3)

          거래코드                 결제일     고객아이디  물품코드  수량
0  T0000000113 2019-02-01 01:36:57  PL563502  S005   1
1  T0000000114 2019-02-01 01:37:23  HD678019  S001   1
2  T0000000115 2019-02-01 02:34:19  HD298120  S003   1

In [67]:
transaction_item_data = pd.merge(
    transaction_data,
    item,
    left_on = "물품코드",
    right_on = "물품코드",
    how="left"
)
transaction_item_data.head(3)

          거래코드                 결제일     고객아이디  물품코드  수량   물품명    물품가격
0  T0000000113 2019-02-01 01:36:57  PL563502  S005   1  PC-E  210000
1  T0000000114 2019-02-01 01:37:23  HD678019  S001   1  PC-A   50000
2  T0000000115 2019-02-01 02:34:19  HD298120  S003   1  PC-C  120000

In [68]:
data = pd.merge(
    transaction_item_data,
    customer,
    on="고객아이디",
    how="left"
)

In [69]:
# 거래금액 생성
data['거래금액'] = data['수량'] * data['물품가격']

In [70]:
# 거래금액 확인
sum (data['거래금액'])

971135000

In [72]:
data.to_pickle('./pkl/data.pkl')