In [54]:
import pandas as pd

df = pd.read_csv("http://114.207.245.181:13000/csv/ynat.csv")
df.head(3)

,guid,title,predefined_news_category,label,url,date,annotations.annotators,annotations.annotations.first-scope,annotations.annotations.second-scope,annotations.annotations.third-scope
0,ynat-v1_train_00000,유튜브 내달 2일까지 크리에이터 지원 공간 운영,IT과학,생활문화,https://news.naver.com/main/read.nhn?mode=LS2D...,2016.06.30. 오전 10:36,"['08', '13', '07']","['생활문화', '생활문화', 'IT과학']","['IT과학', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']"
1,ynat-v1_train_00001,어버이날 맑다가 흐려져…남부지방 옅은 황사,생활문화,생활문화,https://news.naver.com/main/read.nhn?mode=LS2D...,2016.05.08. 오전 5:25,"['14', '13', '07']","['생활문화', '생활문화', '생활문화']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']"
2,ynat-v1_train_00002,내년부터 국가RD 평가 때 논문건수는 반영 않는다,IT과학,사회,https://news.naver.com/main/read.nhn?mode=LS2D...,2016.03.15. 오후 12:00,"['14', '13', '10']","['사회', '사회', '사회']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']"

In [55]:
df['predefined_news_category'].value_counts()

predefined_news_category
세계      8034
정치      7993
IT과학    7852
스포츠     7688
경제      6028
생활문화    6022
사회      2061
Name: count, dtype: int64

In [56]:
df.columns

Index(['guid', 'title', 'predefined_news_category', 'label', 'url', 'date',
       'annotations.annotators', 'annotations.annotations.first-scope',
       'annotations.annotations.second-scope',
       'annotations.annotations.third-scope'],
      dtype='object')

In [57]:
# None 데이터 삭제하기
df.dropna(inplace=True)

In [59]:
df['predefined_news_category'].value_counts()

predefined_news_category
세계      8034
정치      7993
IT과학    7852
스포츠     7688
경제      6028
생활문화    6022
사회      2061
Name: count, dtype: int64

In [76]:
mapping = {
    "세계": 0,
    "정치": 1,
    "IT과학": 2,
    "스포츠": 3,
    "경제": 4,
    "생활문화": 5,
    "사회": 6
}

df['target'] = df['predefined_news_category'].map(mapping)
df

,guid,title,predefined_news_category,label,url,date,annotations.annotators,annotations.annotations.first-scope,annotations.annotations.second-scope,annotations.annotations.third-scope,target
0,ynat-v1_train_00000,유튜브 내달 2일까지 크리에이터 지원 공간 운영,IT과학,생활문화,https://news.naver.com/main/read.nhn?mode=LS2D...,2016.06.30. 오전 10:36,"['08', '13', '07']","['생활문화', '생활문화', 'IT과학']","['IT과학', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']",2
1,ynat-v1_train_00001,어버이날 맑다가 흐려져…남부지방 옅은 황사,생활문화,생활문화,https://news.naver.com/main/read.nhn?mode=LS2D...,2016.05.08. 오전 5:25,"['14', '13', '07']","['생활문화', '생활문화', '생활문화']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']",5
2,ynat-v1_train_00002,내년부터 국가RD 평가 때 논문건수는 반영 않는다,IT과학,사회,https://news.naver.com/main/read.nhn?mode=LS2D...,2016.03.15. 오후 12:00,"['14', '13', '10']","['사회', '사회', '사회']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']",2
3,ynat-v1_train_00003,김명자 신임 과총 회장 원로와 젊은 과학자 지혜 모을 것,IT과학,사회,https://news.naver.com/main/read.nhn?mode=LS2D...,2017.02.28. 오전 9:54,"['16', '11', '15']","['사회', 'IT과학', '사회']","['해당없음', '해당없음', 'IT과학']","['해당없음', '해당없음', '경제']",2
4,ynat-v1_train_00004,회색인간 작가 김동식 양심고백 등 새 소설집 2권 출간,생활문화,생활문화,https://news.naver.com/main/read.nhn?mode=LS2D...,2018.04.03. 오전 7:05,"['03', '02', '12']","['생활문화', '생활문화', '생활문화']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']",5
...,...,...,...,...,...,...,...,...,...,...,...
45673,ynat-v1_train_45673,사우디 아람코 주요 석유시설·유전 드론 공격에 화재,세계,세계,https://news.naver.com/main/read.nhn?mode=LS2D...,2019.09.14. 오후 4:36,"['14', '07', '08']","['세계', '세계', '세계']","['사회', '사회', '해당없음']","['IT과학', '해당없음', '해당없음']",0
45674,ynat-v1_train_45674,박기원 감독 눈치 보지 말고…비예나 눈치 본 건 아닌데,스포츠,스포츠,https://sports.news.naver.com/news.nhn?oid=001...,2019.11.03 17:06,"['09', '13', '18']","['스포츠', '스포츠', '스포츠']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']",3
45675,ynat-v1_train_45675,아시안게임 첫 경기 앞둔 라건아 인도네시아 팬이라도 ...,스포츠,스포츠,https://sports.news.naver.com/news.nhn?oid=001...,2018.08.13 17:54,"['07', '08', '12']","['스포츠', '스포츠', '스포츠']","['해당없음', '해당없음', '해당없음']","['해당없음', '해당없음', '해당없음']",3
45676,ynat-v1_train_45676,트럼프 미중 무역협상 1단계 합의 서명식 가질 것종합,세계,세계,https://news.naver.com/main/read.nhn?mode=LS2D...,2019.12.25. 오후 4:36,"['07', '18', '02']","['세계', '세계', '세계']","['정치', '해당없음', '정치']","['해당없음', '해당없음', '해당없음']",0
45677,ynat-v1_train_45677,극적 역전승 도로공사 GS칼텍스 꺾고 2년 연속 챔프...,스포츠,스포츠,https://sports.news.naver.com/news.nhn?oid=001...,2019.03.19 21:32,"['11', '15', '10']","['스포츠', '스포츠', '스포츠']","['해당없음', '사회', '해당없음']","['해당없음', '해당없음', '해당없음']",3

In [77]:
texts = df['title'].tolist()
labels = df['target'].tolist()

In [78]:
texts = texts[:500]
labels = labels[:500]

In [79]:
import torch
from transformers import AutoTokenizer, AutoModel
from torch.utils.data import DataLoader, TensorDataset

MODEL_NAME = "snunlp/KR-SBERT-V40K-klueNLI-augSTS"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

inputs = tokenizer(
    texts,
    padding=True,
    truncation=True,
    return_tensors="pt",
    max_length=100
)
# inputs

#input_ids = inputs['input_ids']
#attention_mask = inputs['attention_mask']
#labels = torch.tensor(labels, dtype=torch.long)

dataset = TensorDataset(
    inputs['input_ids'],
    inputs['attention_mask'],
    torch.tensor(labels, dtype=torch.long)
)

loader = DataLoader(
    dataset,
    batch_size=4,
    shuffle=True
)

In [80]:
import torch.nn as nn
from transformers import AutoTokenizer, AutoModel

class BertClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.bert = AutoModel.from_pretrained(MODEL_NAME)

        for param in self.bert.parameters():
            param.requires_grad = False

        hidden_size = self.bert.config.hidden_size
        self.dropout = nn.Dropout(0.2)
        self.fc1 = nn.Linear(hidden_size, 7)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(
            input_ids = input_ids,
            attention_mask = attention_mask
        )

        cls = outputs['last_hidden_state'][:, 0]
        x = self.dropout(cls)
        x = self.fc1(x)

        return x

In [81]:
device  = torch.device( 
    "cuda" if torch.cuda.is_available() else "cpu"
)
model = BertClassifier().to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr = 0.001
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [82]:
epochs = 10

for epoch in range( epochs ):
    model.train()
    total_loss = 0
    
    # 추가된 부분
    correct = 0
    total = 0

    for batch in loader:
        input_ids = batch[0].to(device)
        attention_mask = batch[1].to(device)
        labels = batch[2].to(device)

        optimizer.zero_grad() # 기울기 초기화
        logits = model( input_ids = input_ids, attention_mask = attention_mask ) # 모델 학습
        loss = criterion(logits.squeeze(), labels) # 로그 계산
        loss.backward() # 기울기 계산
        optimizer.step() # 가중치 업데이트
        total_loss += loss.item() # 전체 loss값 누적

        # 추가된 부분
        preds = torch.argmax(logits, dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    accuracy = correct / total    

    print ( f"Epoch {epoch+1} Loss { total_loss/len(loader):.4f} Accuracy {accuracy:.4f}"  )    # epoch와 loss값 출력

Epoch 1 Loss 1.2517 Accuracy 0.5840
Epoch 2 Loss 0.5820 Accuracy 0.8260
Epoch 3 Loss 0.4178 Accuracy 0.8880
Epoch 4 Loss 0.3113 Accuracy 0.9140
Epoch 5 Loss 0.2956 Accuracy 0.9260
Epoch 6 Loss 0.2503 Accuracy 0.9300
Epoch 7 Loss 0.2202 Accuracy 0.9380
Epoch 8 Loss 0.2175 Accuracy 0.9360
Epoch 9 Loss 0.1699 Accuracy 0.9620
Epoch 10 Loss 0.1779 Accuracy 0.9440

In [47]:
# mapping의 키 값을 바꾸기
id_to_label = {v: k for k, v in mapping.items()}

print(id_to_label)


def predict_news(text):

    model.eval()

    enc = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=100,
        return_tensors="pt"
    )

    input_ids = ( enc["input_ids"].to(device) )
    attention_mask = ( enc["attention_mask"].to(device) )


    with torch.no_grad():
        logits = model(
            input_ids,
            attention_mask
        )

        pred = torch.argmax(
            logits,
            dim=1
        ).item()

    return id_to_label[pred]


print( predict_news( "삼성전자가 새로운 AI 반도체를 공개했다") )
print( predict_news( "손흥민이 결승골을 터뜨렸다") )
print( predict_news( "국회가 예산안을 통과시켰다") )
print( predict_news(""))

{0: '세계', 1: '정치', 2: 'IT과학', 3: '스포츠', 4: '경제', 5: '생활문화', 6: '사회'}
IT과학
스포츠
정치
경제