In [1]:
import pandas as pd
df = pd.read_csv("http://114.207.245.181:13000/csv/fish01.csv")
df.head()

  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [ ]:
df.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='object')

In [30]:
t1 = {'Species':'어종', 'Weight':'중량', 'Length':'체장', 'Diagonal':'체폭대각선', 'Height':'체고', 'Width':'체폭'}
df.rename(columns=t1, inplace=True)

In [31]:
df

        어종     중량    체장  체폭대각선       체고      체폭
0    Bream  242.0  25.4   30.0  11.5200  4.0200
1    Bream  290.0  26.3   31.2  12.4800  4.3056
2    Bream  340.0  26.5   31.1  12.3778  4.6961
3    Bream  363.0  29.0   33.5  12.7300  4.4555
4    Bream  430.0  29.0   34.0  12.4440  5.1340
..     ...    ...   ...    ...      ...     ...
154  Smelt   12.2  12.2   13.4   2.0904  1.3936
155  Smelt   13.4  12.4   13.5   2.4300  1.2690
156  Smelt   12.2  13.0   13.8   2.2770  1.2558
157  Smelt   19.7  14.3   15.2   2.8728  2.0672
158  Smelt   19.9  15.0   16.2   2.9322  1.8792

[159 rows x 6 columns]

In [4]:
import pandas as pd
df2 = pd.read_csv('./csv/공공도서관_수_및_열람석_수_20260515155845.csv')
df2

      행정구역별       2023     2023.1             2023.2                 2023.3
0     행정구역별  도서관 수 (개)  열람석 수 (개)  1인당 도서관 열람석 수 (개)  주민등록인구수(등록외국인 포함) (명)
1        총계       1224     359316              0.007               52673955
2     서울특별시        187      38183              0.004                9638799
3     부산광역시         45      21262              0.006                3342452
4     대구광역시         46      11487              0.005                2408265
5     인천광역시         58      16048              0.005                3078426
6     광주광역시         27      10185              0.007                1444585
7     대전광역시         25       8884              0.006                1465600
8     울산광역시         20       5778              0.005                1127281
9   세종특별자치시         15       3173              0.008                 392311
10      경기도        309     106148              0.008               14056450
11  강원특별자치도         63      14384              0.009                1551291
12     충청북도         54      10073              0.006                1642335
13     충청남도         62      17708              0.008                2215334
14     전라북도         66      16500              0.009                1794972
15     전라남도         73      21646              0.012                1853327
16     경상북도         70      25782              0.010                2621349
17     경상남도         82      24945              0.007                3340470
18  제주특별자치도         22       7130              0.010                 700708

In [6]:
df2.columns

Index(['행정구역별', '2023', '2023.1', '2023.2', '2023.3'], dtype='object')

In [11]:
t1={'행정구역별':'행정구역', '2023':'도서관수', '2023.1':'열람석수', '2023.2':'1인당열람석수', '2023.3':'등록인구수'}
df2.rename(columns=t1, inplace=True)

In [19]:
df2 = df2.drop(0)

In [23]:
df2.dtypes

행정구역        object
도서관수         int64
열람석수         int64
1인당열람석수    float64
등록인구수        int64
dtype: object

In [22]:
df2['도서관수'] = df2['도서관수'].astype("int64")
df2['열람석수'] = df2['열람석수'].astype("int64")
df2['1인당열람석수'] = df2['1인당열람석수'].astype("float")
df2['등록인구수'] = df2['등록인구수'].astype("int64")
df2

       행정구역  도서관수    열람석수  1인당열람석수     등록인구수
1        총계  1224  359316    0.007  52673955
2     서울특별시   187   38183    0.004   9638799
3     부산광역시    45   21262    0.006   3342452
4     대구광역시    46   11487    0.005   2408265
5     인천광역시    58   16048    0.005   3078426
6     광주광역시    27   10185    0.007   1444585
7     대전광역시    25    8884    0.006   1465600
8     울산광역시    20    5778    0.005   1127281
9   세종특별자치시    15    3173    0.008    392311
10      경기도   309  106148    0.008  14056450
11  강원특별자치도    63   14384    0.009   1551291
12     충청북도    54   10073    0.006   1642335
13     충청남도    62   17708    0.008   2215334
14     전라북도    66   16500    0.009   1794972
15     전라남도    73   21646    0.012   1853327
16     경상북도    70   25782    0.010   2621349
17     경상남도    82   24945    0.007   3340470
18  제주특별자치도    22    7130    0.010    700708

In [28]:
df2['등록인구수'].iloc[1:].sum()

np.int64(52673955)

In [29]:
df2['1인당열람석수'].iloc[1:].mean().round(3)

np.float64(0.007)

In [32]:
df.to_pickle('./pkl/fish.pkl')
df.to_pickle('./pkl/library.pkl')