In [1]:
import pandas as pd
df = pd.read_csv("http://114.207.245.181:13000/csv/student_info.csv")
df

   Student_ID               Name  Age Gender      Grade
0        S001       Thomas Patel   21      M   Freshman
1        S002     Jessica Pierce   20      F     Senior
2        S003   Allison Lopez MD   23      F   Freshman
3        S004        Tiffany Cox   22      F     Junior
4        S005      Martha Vargas   23      F     Senior
..        ...                ...  ...    ...        ...
95       S096   Matthew Martinez   23      F   Freshman
96       S097     Samantha Wells   24      M     Senior
97       S098       Jamie Cooper   21      F   Freshman
98       S099         Kyle Hines   19      M  Sophomore
99       S100  Benjamin Martinez   22      F     Senior

[100 rows x 5 columns]

In [2]:
# 컬럼명을 확인후에 변경
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Grade'], dtype='object')

In [6]:
t1 = {"Student_ID":"학생아이디", "Name":"이름", "Age":"나이", "Gender":"성별", "Grade":"학년"}
df.rename(columns=t1, inplace=True)

In [9]:
df

   학생아이디                 이름  나이 성별         학년
0   S001       Thomas Patel  21  M   Freshman
1   S002     Jessica Pierce  20  F     Senior
2   S003   Allison Lopez MD  23  F   Freshman
3   S004        Tiffany Cox  22  F     Junior
4   S005      Martha Vargas  23  F     Senior
..   ...                ...  .. ..        ...
95  S096   Matthew Martinez  23  F   Freshman
96  S097     Samantha Wells  24  M     Senior
97  S098       Jamie Cooper  21  F   Freshman
98  S099         Kyle Hines  19  M  Sophomore
99  S100  Benjamin Martinez  22  F     Senior

[100 rows x 5 columns]

In [10]:
df.to_pickle('./pkl/student.pkl')

In [1]:
import pandas as pd
df = pd.read_pickle('./pkl/student.pkl')
df

   학생아이디                 이름  나이 성별         학년
0   S001       Thomas Patel  21  M   Freshman
1   S002     Jessica Pierce  20  F     Senior
2   S003   Allison Lopez MD  23  F   Freshman
3   S004        Tiffany Cox  22  F     Junior
4   S005      Martha Vargas  23  F     Senior
..   ...                ...  .. ..        ...
95  S096   Matthew Martinez  23  F   Freshman
96  S097     Samantha Wells  24  M     Senior
97  S098       Jamie Cooper  21  F   Freshman
98  S099         Kyle Hines  19  M  Sophomore
99  S100  Benjamin Martinez  22  F     Senior

[100 rows x 5 columns]

In [2]:
t1 = { "M":"남", "F":"여"}
df['성별'] = df['성별'].map(t1)
df

   학생아이디                 이름  나이 성별         학년
0   S001       Thomas Patel  21  남   Freshman
1   S002     Jessica Pierce  20  여     Senior
2   S003   Allison Lopez MD  23  여   Freshman
3   S004        Tiffany Cox  22  여     Junior
4   S005      Martha Vargas  23  여     Senior
..   ...                ...  .. ..        ...
95  S096   Matthew Martinez  23  여   Freshman
96  S097     Samantha Wells  24  남     Senior
97  S098       Jamie Cooper  21  여   Freshman
98  S099         Kyle Hines  19  남  Sophomore
99  S100  Benjamin Martinez  22  여     Senior

[100 rows x 5 columns]

In [4]:
df['학년'].value_counts()

학년
1학년    32
4학년    30
2학년    20
3학년    18
Name: count, dtype: int64

In [3]:
t1 = { "Freshman":"1학년", "Sophomore":"2학년", "Junior":"3학년", "Senior":"4학년" }
df['학년'] = df['학년'].map(t1)
df

   학생아이디                 이름  나이 성별   학년
0   S001       Thomas Patel  21  남  1학년
1   S002     Jessica Pierce  20  여  4학년
2   S003   Allison Lopez MD  23  여  1학년
3   S004        Tiffany Cox  22  여  3학년
4   S005      Martha Vargas  23  여  4학년
..   ...                ...  .. ..  ...
95  S096   Matthew Martinez  23  여  1학년
96  S097     Samantha Wells  24  남  4학년
97  S098       Jamie Cooper  21  여  1학년
98  S099         Kyle Hines  19  남  2학년
99  S100  Benjamin Martinez  22  여  4학년

[100 rows x 5 columns]

In [5]:
df1 = pd.read_csv("http://114.207.245.181:13000/csv/score_info.csv")
df1

   Student_ID  Math  Science  English  History  Physical_Education
0        S001    76       65       88       91                  78
1        S002    75       94       76       70                  83
2        S003    86       69       62       61                  67
3        S004    72       62       67       78                  83
4        S005    74       65       92       84                  60
..        ...   ...      ...      ...      ...                 ...
95       S096    79       81       61       98                  60
96       S097    99       85       92       84                  97
97       S098    60       75       90       85                  73
98       S099    64       90       87       88                  96
99       S100    62       61       97       99                  65

[100 rows x 6 columns]

In [6]:
t1 = { "Student_ID":"학생아이디", "Math":"수학", "Science":"과학", 
      "English":"영어", "History":"역사", "Physical_Education":"체육" }
df1 = df1.rename(columns=t1)
df1

   학생아이디  수학  과학  영어  역사  체육
0   S001  76  65  88  91  78
1   S002  75  94  76  70  83
2   S003  86  69  62  61  67
3   S004  72  62  67  78  83
4   S005  74  65  92  84  60
..   ...  ..  ..  ..  ..  ..
95  S096  79  81  61  98  60
96  S097  99  85  92  84  97
97  S098  60  75  90  85  73
98  S099  64  90  87  88  96
99  S100  62  61  97  99  65

[100 rows x 6 columns]

In [ ]:
df2 = pd.merge(df, df1, on="학생아이디")
df2.head(3)

   학생아이디                 이름  나이 성별   학년  수학  과학  영어  역사  체육
0   S001       Thomas Patel  21  남  1학년  76  65  88  91  78
1   S002     Jessica Pierce  20  여  4학년  75  94  76  70  83
2   S003   Allison Lopez MD  23  여  1학년  86  69  62  61  67
3   S004        Tiffany Cox  22  여  3학년  72  62  67  78  83
4   S005      Martha Vargas  23  여  4학년  74  65  92  84  60
..   ...                ...  .. ..  ...  ..  ..  ..  ..  ..
95  S096   Matthew Martinez  23  여  1학년  79  81  61  98  60
96  S097     Samantha Wells  24  남  4학년  99  85  92  84  97
97  S098       Jamie Cooper  21  여  1학년  60  75  90  85  73
98  S099         Kyle Hines  19  남  2학년  64  90  87  88  96
99  S100  Benjamin Martinez  22  여  4학년  62  61  97  99  65

[100 rows x 10 columns]

In [8]:
df2['합계'] = df2['수학'] + df2['과학'] + df2['영어'] + df2['역사'] + df2['체육']
df2

   학생아이디                 이름  나이 성별   학년  수학  과학  영어  역사  체육   합계
0   S001       Thomas Patel  21  남  1학년  76  65  88  91  78  398
1   S002     Jessica Pierce  20  여  4학년  75  94  76  70  83  398
2   S003   Allison Lopez MD  23  여  1학년  86  69  62  61  67  345
3   S004        Tiffany Cox  22  여  3학년  72  62  67  78  83  362
4   S005      Martha Vargas  23  여  4학년  74  65  92  84  60  375
..   ...                ...  .. ..  ...  ..  ..  ..  ..  ..  ...
95  S096   Matthew Martinez  23  여  1학년  79  81  61  98  60  379
96  S097     Samantha Wells  24  남  4학년  99  85  92  84  97  457
97  S098       Jamie Cooper  21  여  1학년  60  75  90  85  73  383
98  S099         Kyle Hines  19  남  2학년  64  90  87  88  96  425
99  S100  Benjamin Martinez  22  여  4학년  62  61  97  99  65  384

[100 rows x 11 columns]

In [9]:
df2['평균'] = df2['합계'] / 5
df2

   학생아이디                 이름  나이 성별   학년  수학  과학  영어  역사  체육   합계    평균
0   S001       Thomas Patel  21  남  1학년  76  65  88  91  78  398  79.6
1   S002     Jessica Pierce  20  여  4학년  75  94  76  70  83  398  79.6
2   S003   Allison Lopez MD  23  여  1학년  86  69  62  61  67  345  69.0
3   S004        Tiffany Cox  22  여  3학년  72  62  67  78  83  362  72.4
4   S005      Martha Vargas  23  여  4학년  74  65  92  84  60  375  75.0
..   ...                ...  .. ..  ...  ..  ..  ..  ..  ..  ...   ...
95  S096   Matthew Martinez  23  여  1학년  79  81  61  98  60  379  75.8
96  S097     Samantha Wells  24  남  4학년  99  85  92  84  97  457  91.4
97  S098       Jamie Cooper  21  여  1학년  60  75  90  85  73  383  76.6
98  S099         Kyle Hines  19  남  2학년  64  90  87  88  96  425  85.0
99  S100  Benjamin Martinez  22  여  4학년  62  61  97  99  65  384  76.8

[100 rows x 12 columns]

In [10]:
# min은 예시) 1 2 2 4
df2['석차'] = df2['합계'].rank(method="min", ascending=False).astype(int)
df2

   학생아이디                 이름  나이 성별   학년  수학  과학  영어  역사  체육   합계    평균  석차
0   S001       Thomas Patel  21  남  1학년  76  65  88  91  78  398  79.6  51
1   S002     Jessica Pierce  20  여  4학년  75  94  76  70  83  398  79.6  51
2   S003   Allison Lopez MD  23  여  1학년  86  69  62  61  67  345  69.0  99
3   S004        Tiffany Cox  22  여  3학년  72  62  67  78  83  362  72.4  90
4   S005      Martha Vargas  23  여  4학년  74  65  92  84  60  375  75.0  76
..   ...                ...  .. ..  ...  ..  ..  ..  ..  ..  ...   ...  ..
95  S096   Matthew Martinez  23  여  1학년  79  81  61  98  60  379  75.8  71
96  S097     Samantha Wells  24  남  4학년  99  85  92  84  97  457  91.4   2
97  S098       Jamie Cooper  21  여  1학년  60  75  90  85  73  383  76.6  68
98  S099         Kyle Hines  19  남  2학년  64  90  87  88  96  425  85.0  17
99  S100  Benjamin Martinez  22  여  4학년  62  61  97  99  65  384  76.8  66

[100 rows x 13 columns]

In [11]:
df2.head()

  학생아이디                이름  나이 성별   학년  수학  과학  영어  역사  체육   합계    평균  석차
0  S001      Thomas Patel  21  남  1학년  76  65  88  91  78  398  79.6  51
1  S002    Jessica Pierce  20  여  4학년  75  94  76  70  83  398  79.6  51
2  S003  Allison Lopez MD  23  여  1학년  86  69  62  61  67  345  69.0  99
3  S004       Tiffany Cox  22  여  3학년  72  62  67  78  83  362  72.4  90
4  S005     Martha Vargas  23  여  4학년  74  65  92  84  60  375  75.0  76

In [ ]:
# 학년별 합계 평균 구하기
# groupby([학년])[[]].연산(sum, mean, min, max, ...)
df2.groupby(['학년'])[['합계']].mean().round(2)

         합계
학년
1학년  399.12
2학년  400.85
3학년  393.67
4학년  398.60

In [ ]:
df2.groupby(['학년'])[['수학', '영어']].agg(["mean", "sum", "min", "max"])

            수학                       영어
          mean   sum min max       mean   sum min max
학년
1학년  82.968750  2655  60  99  81.906250  2621  61  98
2학년  80.300000  1606  61  98  80.500000  1610  62  93
3학년  75.166667  1353  60  97  79.166667  1425  60  99
4학년  78.600000  2358  60  99  81.266667  2438  62  98

In [15]:
df2.to_pickle('./pkl/20260515_student.pkl')